-- Club members register from WFC_2026_Members__Players_copy.xlsx
insert into public.club_members (membership_number, full_name, membership_type, email, phone, postal_address) values
  (1, 'Fred Hopkins', 'Life Member', NULL, NULL, '8 Victoria Street, Wallaroo, SA, 5556'),
  (2, 'Mrs June Schofield', 'Life Member', NULL, NULL, NULL),
  (3, 'Mick Mellow', 'Life Member', NULL, NULL, '3 Warmington Esp, Wallaroo S.A. 5556'),
  (4, 'Robert Newhousen', 'Life Member', NULL, NULL, '22 Scotland St, Wallaroo S.A. 5556'),
  (5, 'Mrs Margaret Newhousen', 'Life Member', NULL, NULL, '22 Scotland St, Wallaroo S.A. 5556'),
  (6, 'John Evans', 'Life Member', NULL, NULL, '1 Jones St, Wallaroo S.A. 5556'),
  (7, 'Bruce Hann', 'Life Member', NULL, NULL, '10 Cornwall Street, Wallaroo, SA, 5556'),
  (8, 'Paul Willment', 'Life Member', NULL, NULL, '18 Evans Rd North, Wallaroo S.A. 5556'),
  (9, 'Brian (Bra) Cooper', 'Life Member', NULL, NULL, '13 Young St, Wallaroo S.A. 5556'),
  (10, 'Anthony Peters', 'Life Member', NULL, NULL, '85 Graves St, Kadina S.A. 5554'),
  (11, 'Bronte Smith', 'Life Member', NULL, NULL, '76 East Tce, Wallaroo, SA, 5556'),
  (12, 'Mrs Judith Johns', 'Life Member', NULL, NULL, '9 Ernest Terrace, Wallaroo,SA,5556'),
  (13, 'Steven Scholes', 'Life Member', NULL, NULL, '7 Ketch Place, Wallaroo,SA, 5556'),
  (14, 'Gary Cooper', 'Life Member', NULL, NULL, NULL),
  (15, 'Sam Snodgrass', 'Life Member', NULL, NULL, NULL),
  (16, 'Mrs Jenny Penhall', 'Life Member', NULL, NULL, '3 Matta Street, Wallaroo, SA, 5556'),
  (17, 'Merv Miller', 'Life Member', NULL, NULL, 'Star of the Sea, Wallaroo'),
  (18, 'Wayne Johns', 'Life Member', NULL, NULL, NULL),
  (19, 'Kym Flint', 'Life Member', 'kymflint23@gmail.com', NULL, '34 stately way, wallaroo,sa,5556'),
  (20, 'David Murphy', 'Life Member', NULL, NULL, NULL),
  (21, 'Dennis Miller', 'Life Member', NULL, NULL, '52 Olive Parade, New Town,SA,5554'),
  (22, 'Scott Grillett', 'Life Member', NULL, NULL, '18, Wildman Street, Wallaroo,SA,5556'),
  (23, 'Chris Johns', 'Life Member', 'Ky', NULL, NULL),
  (24, 'Philip Haylock', 'Life Member', NULL, NULL, '15 Elizabeth Street, Wallaroo,SA, 5556'),
  (25, 'Mark Depledge', 'Life Member', 'katrinadepledge@hotmail.com', '0407 233 219', '15 Ernest Terrace, Wallaroo, SA, 5556'),
  (26, 'Janet Errington', 'Life Member', 'per41120@bigpond.net.au', NULL, '11 Evans Road North, Wallaroo SA, 5556'),
  (27, 'Des Westlake', 'Life Member', NULL, NULL, '52 Charles Terrace, Wallaroo, SA, 5556'),
  (28, 'Geoff Jarman', 'Life Member', NULL, NULL, '7 Ernest Terrace, Wallaroo, SA, 5556'),
  (29, 'Geoff James', 'Life Member', NULL, NULL, '22 Victoria Street, Wallaroo, SA, 5556'),
  (30, 'Jason Niotis', 'Life Member', 'jniotis@bigpond.com', '0417 818 943', NULL),
  (31, 'Andy West', 'Life Member', 'awest1@bigpond.net.au', '0418 859 646', '31 Errington Street, Wallaroo,SA,5556'),
  (32, 'Scott Mumford', 'Committee', 'robustworx42@gmail.com', '0458 958 995', '51 Beare Street, Wallaroo,SA, 5556'),
  (33, 'Nathan Wright', 'Committee', 'nwright000013@gmail.com', NULL, NULL),
  (34, 'Thomas Depledge', 'Committee', 'thomasdepledge@outlook.com', '0422 354 912', '15 Ernest Tce, Wallaroo,SA,5556'),
  (35, 'Sharne Thomson', 'Committee', 'sharne.thomson@bigpond.com', NULL, NULL),
  (36, 'Michael West', 'Committee', 'michaelwest10@outlook.com', NULL, NULL),
  (37, 'Shaun Miller', 'Committee', 'mail4pup25@gmail.com', NULL, NULL),
  (38, 'Jamie Yeates', 'Committee', 'yata@bigpond.com', NULL, NULL),
  (39, 'Todd Summerton', 'Committee', 'toddsummo@gmail.com', NULL, NULL),
  (40, 'Darrell Woods', 'Committee', 'darrellwoods@live.com', NULL, NULL),
  (41, 'Andrew Dekort', 'Committee', 'knackers02@hotmail.com', NULL, NULL),
  (42, 'Kristy Smith', 'Committee', 'kristy.smith@stmm.catholic.edu.au', NULL, NULL),
  (43, 'Nathan Murphy', 'Committee', 'nathanmurphy90@outlook.com', NULL, NULL),
  (44, 'Lindsay Smith', 'JNR Committee', 'linz17@hotmail.com.au', NULL, NULL),
  (45, 'Emily Donnell', 'JNR Committee', 'emily.donnell@bigpond.com', '0416105581', NULL),
  (46, 'Hayden Donnell', 'JNR Committee', 'donnellhe@bigpond.com', '0427242200', NULL),
  (47, 'Nathan Clifford', 'JNR Committee', 'sarahandnathan@bigpond.com', '0408176830', NULL),
  (48, 'Sarah Clifford', 'JNR Committee', 'sarahandnathan@bigpond.com', '0408176830', NULL),
  (49, 'Matt Robinson', 'JNR Committee', 'melrobinson07@hotmail.com', NULL, NULL),
  (50, 'Jody Duif', 'JNR Committee', 'jody-lee09@hotmail.com', '0431347626', NULL),
  (51, 'Lachy Duif', 'JNR Committee', NULL, NULL, NULL),
  (52, 'Teressa Linke', 'JNR Committee', 'teressalinke@gmail.com', '0432907507', NULL),
  (53, 'Claire Dekort', 'JNR Committee', 'mollycharlie2@hotmail.com', NULL, NULL),
  (54, 'Natesha Davey', 'JNR Committee', 'nateshadavey9@outlook.com', NULL, NULL),
  (55, 'Caine Kaiser', 'Player', 'cainekaiser@icloud.com', '0461 557 313', '4 Schiling Street, Kadina, SA,5554'),
  (56, 'Daniel Staines', 'Player', 'danielstaines127@gmail.com', '0400 877 965', '14 Thyer Street, Newtown,SA,5554'),
  (57, 'Seaside Vet Surgery', 'Bronze Sposnsors', 'amanda@seasidevet.com.au', NULL, NULL),
  (58, 'Enfield Furnishers', 'Bronze Sposnsors', 'efurn@enfurn.com.au', '88212311', '16 Graves Street, Kadina,SA,5554'),
  (59, 'Murray Pest Control YP', 'Diamond Level 1', 'thommo44@bigpond.com', '0409 677 844', NULL),
  (60, 'Murray Pest Control YP', 'Diamond Level 1', 'thommo44@bigpond.com', '0409 677 844', NULL),
  (61, 'St Mary Mackillop', 'Gold Sponsor', 'finance@stmm.catholic.edu.au', '88215800', NULL),
  (62, 'St Mary Mackillop', 'Gold Sponsor', 'finance@stmm.catholic.edu.au', '88215800', NULL),
  (63, 'Rosewarnes', 'Bronze Sposnsors', 'tom.rosewarne@jhrosewarne.com.au', '8821 1111', NULL),
  (64, 'Bennett Painting & Decorating Pty Ltd', 'Diamond Level 1', 'admin@jmbennett.com.au', NULL, NULL),
  (65, 'Bennett Painting & Decorating Pty Ltd', 'Diamond Level 1', 'admin@jmbennett.com.au', NULL, NULL),
  (66, 'Burfit Concreting', 'Bronze Sposnsors', 'maburfitt@bigpond.com', NULL, NULL),
  (67, 'Kurlben Painting', 'Silver Sponsors', 'kurlbenpainting@gmail.com', NULL, NULL),
  (68, 'Kurlben Painting', 'Silver Sponsors', 'kurlbenpainting@gmail.com', NULL, NULL),
  (69, 'Leanic Civil', 'Platinum', 'admin@leanic.com.au', '0429 783 366', NULL),
  (70, 'Leanic Civil', 'Platinum', 'admin@leanic.com.au', '0429 783 366', NULL),
  (71, 'Leanic Civil', 'Platinum', 'admin@leanic.com.au', '0429 783 366', NULL),
  (72, 'Craig Fletcher', 'Silver Sponsors', 'cfletcherm259@bigpond.com', '0428 233 792', NULL),
  (73, 'Wallaroo Barber Shop', 'Club Sponsor', 'wallaroobarbershop@gmail.com', NULL, NULL),
  (74, 'Robust Worx', 'Gold Sponsor', 'robustworx42@gmail.com', NULL, NULL),
  (75, 'Robust Worx', 'Gold Sponsor', 'robustworx42@gmail.com', NULL, NULL),
  (76, 'Robust Worx', 'Gold Sponsor', 'robustworx42@gmail.com', NULL, NULL),
  (77, 'Wallaroo Office Beach Tourist Park', 'Silver Sponsors', 'stay@wallaroobeachfronttouristpark.com.au', NULL, NULL),
  (78, 'Wallaroo Office Beach Tourist Park', 'Silver Sponsors', 'stay@wallaroobeachfronttouristpark.com.au', NULL, NULL),
  (79, 'Peninsula Toyota', 'Silver Sponsors', 'admin3@gunnings.com.au', NULL, NULL),
  (80, 'Peninsula Toyota', 'Silver Sponsors', 'admin3@gunnings.com.au', NULL, NULL),
  (81, 'YP Fire & Safety', 'Bronze Sposnsors', 'bob@fessa.com.au', NULL, NULL),
  (82, 'Kadina Tyre & Auto', 'Bronze Sposnsors', 'kadinatyres@bigpond.com', NULL, NULL),
  (83, 'Wallaroo Hotel', 'Bronze Sposnsors', 'paul@wallaroohotel.com.au', NULL, NULL),
  (84, 'YP Coaches', 'Bronze Sposnsors', 'kylie@ypcoaches.com.au', '8821 2755', NULL),
  (86, 'T Ports', 'VIP', 'hayley.lewis@tports.com', '0418 838 872', NULL),
  (87, 'T Ports', 'VIP', 'hayley.lewis@tports.com', '0418 838 872', NULL),
  (88, 'T Ports', 'VIP', 'hayley.lewis@tports.com', '0418 838 872', NULL),
  (89, 'T Ports', 'VIP', 'hayley.lewis@tports.com', '0418 838 872', NULL),
  (90, 'Hallett Group', 'VIP', 'Ryan.paxton@hallett.com.au', NULL, NULL),
  (91, 'Hallett Group', 'VIP', 'Ryan.paxton@hallett.com.au', NULL, NULL),
  (92, 'Hallett Group', 'VIP', 'Ryan.paxton@hallett.com.au', NULL, NULL),
  (93, 'Hallett Group', 'VIP', 'Ryan.paxton@hallett.com.au', NULL, NULL),
  (94, 'Northbeach Caravan Park', 'VIP', 'stay@wallarooholidaypark.com.au', NULL, NULL),
  (95, 'Northbeach Caravan Park', 'VIP', 'stay@wallarooholidaypark.com.au', NULL, NULL),
  (96, 'Northbeach Caravan Park', 'VIP', 'stay@wallarooholidaypark.com.au', NULL, NULL),
  (97, 'Northbeach Caravan Park', 'VIP', 'stay@wallarooholidaypark.com.au', NULL, NULL),
  (98, 'Cornucopia Hotel', 'VIP', 'cornyhotel@gmail.com', NULL, NULL),
  (99, 'Cornucopia Hotel', 'VIP', 'cornyhotel@gmail.com', NULL, NULL),
  (100, 'Cornucopia Hotel', 'VIP', 'cornyhotel@gmail.com', NULL, NULL),
  (101, 'Cornucopia Hotel', 'VIP', 'cornyhotel@gmail.com', NULL, NULL),
  (102, 'Subway Kadina', 'Platinum', 'lindsay@allsub.net.au', NULL, NULL),
  (103, 'Subway Kadina', 'Platinum', 'lindsay@allsub.net.au', NULL, NULL),
  (104, 'Y.P Marine', 'Platinum', 'admin@ypmarine.com.au', NULL, NULL),
  (105, 'Y.P Marine', 'Platinum', 'admin@ypmarine.com.au', NULL, NULL),
  (106, 'M.A Skinners Contractors', 'Bronze Sponsor', 'sales@skinners.net.au', NULL, NULL),
  (109, 'Fence It', 'Gold Sponsor', 'fenceityp@gmail.com', NULL, NULL),
  (110, 'Fence It', 'Gold Sponsor', 'fenceityp@gmail.com', NULL, NULL),
  (111, 'Fence It', 'Gold Sponsor', 'fenceityp@gmail.com', NULL, NULL),
  (112, 'The Shores Eatery', 'Silver Sponsors', 'accounts@theshoreseatery.com', '0400 644 499', NULL),
  (113, 'The Shores Eatery', 'Silver Sponsors', 'accounts@theshoreseatery.com', '0400 644 499', NULL),
  (116, 'NYP Car Fix', 'Silver Sponsors', 'service@nypcarfix.com.au', '8821 3388', NULL),
  (117, 'NYP Car Fix', 'Silver Sponsors', 'service@nypcarfix.com.au', '8821 3388', NULL),
  (118, 'Drakes', 'Silver Sponsors', 'wallaroo@drakes.com.au', NULL, NULL),
  (119, 'Drakes', 'Silver Sponsors', 'wallaroo@drakes.com.au', NULL, NULL),
  (120, 'Format Concreting', 'Bronze Sposnsors', 'format@adam.com.au', NULL, NULL),
  (121, 'YP Country Times', 'Bronze Sposnsors', 'ypct@ypct.com.au', NULL, NULL),
  (122, 'Copy King/Goodyear', 'Bronze Sposnsors', 'print@copyking.com.au', NULL, NULL),
  (123, 'Abraham Air', 'Bronze Sposnsors', 'abraham.air@outlook.com', NULL, NULL),
  (124, 'Earle Signs', 'Bronze Sposnsors', 'mitch@earlesigns.com.au', NULL, NULL),
  (125, 'Peninsula Nursery', 'Bronze Sposnsors', 'peninsula@nurery@gmail.com', NULL, NULL),
  (126, 'Leo Nadich', 'Silver Parton', 'nadich@bigpond.com', '0438505492', NULL),
  (127, 'Peninsula Insurance', 'Bronze Sposnsors', 'enquiries@peninsulainsurance.com.au', NULL, NULL),
  (128, 'Skinners Family Funerals', 'Club Sponsor', 'enquiries@sffuerals.com.au', NULL, NULL),
  (129, 'Charlie Hines', 'Player', 'kadina@sportspower.com.au', NULL, NULL),
  (131, 'Kyle Power', 'Player', 'kshanepower@gmail.com', NULL, NULL),
  (132, 'G&J East', 'Club Sponsor', 'admin@gjeast.com.au', NULL, NULL),
  (133, 'BHS', 'Diamond Level 2', 'mpboehm@gmail.com', NULL, NULL),
  (134, 'Jeff White Mechanical', 'Silver Sponsors', 'karen71.white@gmail.com', '0438 876 606', NULL),
  (135, 'Jeff White Mechanical', 'Silver Sponsors', 'karen71.white@gmail.com', '0438 876 606', NULL),
  (136, 'Copper Coast Funerals', 'Bronze Sposnsors', 'coppercoastfunerals@bigpond.com', NULL, NULL),
  (137, 'Keepin it Clean', 'Bronze Sposnsors', 'kic2025@hotmail.com', '0467 862 764', NULL),
  (138, 'YP Shade Solutions', 'Platinum', 'ypshadesolutions@gmail.com', NULL, NULL),
  (139, 'YP Shade Solutions', 'Platinum', 'ypshadesolutions@gmail.com', NULL, NULL),
  (140, 'Loctite Storage', 'Bronze Sposnsors', 'kymflint23@gmail.com', NULL, NULL),
  (141, 'Larwoods', 'Bronze Sposnsors', 'office@larwoods.com.au', NULL, NULL),
  (142, 'MM Electrical', 'Bronze Sposnsors', 'mark.aldridge@mmem.com.au', NULL, NULL),
  (143, 'A1 Auto', 'Club Sponsor', 'a1autocars@outlook.com', NULL, NULL),
  (144, 'Sports Power', 'Gold Sponsor', 'kadina@sportspower.com.au', NULL, NULL),
  (145, 'Sports Power', 'Gold Sponsor', 'kadina@sportspower.com.au', NULL, NULL),
  (146, 'Sports Power', 'Gold Sponsor', 'kadina@sportspower.com.au', NULL, NULL),
  (147, 'Pirie Signs & Designs', 'VIP', 'info@piriesigns.com.au', NULL, NULL),
  (148, 'Pirie Signs & Designs', 'VIP', 'info@piriesigns.com.au', NULL, NULL),
  (149, 'Pirie Signs & Designs', 'VIP', 'info@piriesigns.com.au', NULL, NULL),
  (150, 'Pirie Signs & Designs', 'VIP', 'info@piriesigns.com.au', NULL, NULL),
  (151, 'DD''s Air Conditioning & Hygiene Services', 'VIP', 'dunko7@yahoo.com.au', '0417859298', NULL),
  (152, 'DD''s Air Conditioning & Hygiene Services', 'VIP', 'dunko7@yahoo.com.au', '0417859298', NULL),
  (153, 'DD''s Air Conditioning & Hygiene Services', 'VIP', 'dunko7@yahoo.com.au', '0417859298', NULL),
  (154, 'DD''s Air Conditioning & Hygiene Services', 'VIP', 'dunko7@yahoo.com.au', '0417859298', NULL),
  (155, 'Wallaroo Metal Fab', 'Gold Sponsor', 'kerran@ritewayfarming.com.au', NULL, NULL),
  (156, 'Wallaroo Metal Fab', 'Gold Sponsor', 'kerran@ritewayfarming.com.au', NULL, NULL),
  (157, 'Wallaroo Metal Fab', 'Gold Sponsor', 'kerran@ritewayfarming.com.au', NULL, NULL),
  (158, 'All Creek', 'Gold Sponsor', 'admin@johnsfarming.com.au', NULL, NULL),
  (159, 'All Creek', 'Gold Sponsor', 'admin@johnsfarming.com.au', NULL, NULL),
  (160, 'All Creek', 'Gold Sponsor', 'admin@johnsfarming.com.au', NULL, NULL),
  (161, 'YP Linen', 'Gold Sponsor', 'accounts@yplinen.com.au', NULL, NULL),
  (162, 'YP Linen', 'Gold Sponsor', 'accounts@yplinen.com.au', NULL, NULL),
  (163, 'YP Linen', 'Gold Sponsor', 'accounts@yplinen.com.au', NULL, NULL),
  (164, 'Cade Angus', 'Gold Sponsor', 'cadeangus.plumbingandgas@gmail.com', NULL, NULL),
  (165, 'Cade Angus', 'Gold Sponsor', 'cadeangus.plumbingandgas@gmail.com', NULL, NULL),
  (166, 'Cade Angus', 'Gold Sponsor', 'cadeangus.plumbingandgas@gmail.com', NULL, NULL),
  (167, 'T.R Depledge Gardening & Maintenance', 'Platinum', 't.rdepledge@outlook.com', NULL, NULL),
  (168, 'T.R Depledge Gardening & Maintenance', 'Platinum', 't.rdepledge@outlook.com', NULL, NULL),
  (169, 'T.R Depledge Gardening & Maintenance', 'Platinum', 't.rdepledge@outlook.com', NULL, NULL),
  (170, 'Forty Winks', 'Gold Sponsor', 'daverogers@fortywinks.com.au', NULL, NULL),
  (171, 'Forty Winks', 'Gold Sponsor', 'daverogers@fortywinks.com.au', NULL, NULL),
  (172, 'Forty Winks', 'Gold Sponsor', 'daverogers@fortywinks.com.au', NULL, NULL),
  (173, 'YP Mini Diggers', 'Gold Sponsor', 'dunno31@bigpond.com', NULL, NULL),
  (174, 'YP Mini Diggers', 'Gold Sponsor', 'dunno31@bigpond.com', NULL, NULL),
  (175, 'YP Mini Diggers', 'Gold Sponsor', 'dunno31@bigpond.com', NULL, NULL),
  (176, 'Weeroona Hotel', 'Gold Sponsor', 'grant.summerton36@gmail.com/lee-anne17@hotmail.com', NULL, NULL),
  (177, 'Weeroona Hotel', 'Gold Sponsor', 'grant.summerton36@gmail.com/lee-anne17@hotmail.com', NULL, NULL),
  (178, 'Weeroona Hotel', 'Gold Sponsor', 'grant.summerton36@gmail.com/lee-anne17@hotmail.com', NULL, NULL),
  (179, 'Anglers Inn Hotel', 'Gold Sponsor', 'scott@anglersinn.com.au', NULL, NULL),
  (180, 'Anglers Inn Hotel', 'Gold Sponsor', 'scott@anglersinn.com.au', NULL, NULL),
  (181, 'Anglers Inn Hotel', 'Gold Sponsor', 'scott@anglersinn.com.au', NULL, NULL),
  (182, 'Copper Club', 'Gold Sponsor', 'golf@copperclub.com.au', NULL, NULL),
  (183, 'Copper Club', 'Gold Sponsor', 'golf@copperclub.com.au', NULL, NULL),
  (184, 'Copper Club', 'Gold Sponsor', 'golf@copperclub.com.au', NULL, NULL),
  (185, 'Best Pizza', 'Silver Sponsors', 'bestpizzawallaroo@gmail.com', NULL, NULL),
  (186, 'Best Pizza', 'Silver Sponsors', 'bestpizzawallaroo@gmail.com', NULL, NULL),
  (187, 'Prince Edward Hotel', 'Silver Sponsors', 'princeedwardhotel@gmail.com', NULL, NULL),
  (188, 'Prince Edward Hotel', 'Silver Sponsors', 'princeedwardhotel@gmail.com', NULL, NULL),
  (189, 'Wardle Co', 'Silver Sponsors', 'accounts@wardleco.com.au', '8633 4511', NULL),
  (190, 'Wardle Co', 'Silver Sponsors', 'accounts@wardleco.com.au', '8633 4511', NULL),
  (191, 'Nurtien Ag', 'Bronze Sposnsors', 'accountsspayable@nutrien.com.au', '8821 2522', NULL),
  (192, 'Kadina Elertical', 'Bronze Sposnsors', 'kadina@retravision.com.au', NULL, '12 Ireland Street Wallaroo 5556'),
  (193, 'Jack Spetics', 'Bronze Sposnsors', NULL, '0408 859 181', NULL),
  (194, 'Emmets', 'Bronze Sposnsors', 'nbruce@emmetts.com.au', NULL, NULL),
  (195, 'Country Living Homes', 'Bronze Sposnsors', 'emmac@clhg.com.au', NULL, NULL),
  (196, 'Mac villas', 'Club Sponsor', 'macsvillas@yp-connect.net', NULL, NULL),
  (197, 'Weeroona Hotel Partons Club', 'Club Sponsor', 'awest1@bigpond.net.au', NULL, NULL),
  (198, 'Crafers Garden Centre and Landscape Supplies', 'Bronze Sposnsors', 'chris@crafersgardencentre.com.au', NULL, NULL),
  (199, 'Lachlan Elliot', 'Player', 'lachlan.elliot360@gmail.com', NULL, NULL),
  (200, 'Jayden Steer', 'Player', 'jaydensteer05@gmail.com', NULL, NULL),
  (201, 'Perry''s Fuel', 'Club Sponsor', 'sponsorship@perrys.com.au', NULL, NULL),
  (202, 'Newberry Chemist', 'Club', 'newbery.kadina@nunet.com.au', NULL, NULL),
  (203, 'Microsytems Support', 'Bronze', 'sales@mssupport.net.au', NULL, NULL),
  (204, 'Ray White Yorke Peninsula Shaun Miller', 'Bronze', 'shaun.miller@raywhite.com', NULL, NULL),
  (205, 'Westlake Excavations', 'Silver', 'dylanwesty@yahoo.com', NULL, NULL),
  (206, 'Westlake Excavations', 'Silver', 'dylanwesty@yahoo.com', NULL, NULL),
  (207, 'Maritime Constuctions', 'Gold Sponsor', 'info@maritimecon.com.au', NULL, NULL),
  (208, 'Maritime Constuctions', 'Gold Sponsor', 'info@maritimecon.com.au', NULL, NULL),
  (209, 'Maritime Constuctions', 'Gold Sponsor', 'info@maritimecon.com.au', NULL, NULL),
  (210, NULL, NULL, NULL, NULL, NULL),
  (211, 'Luke Hann', 'Player', 'hannd69@hotmail.com', '0438142666', NULL),
  (212, 'Terrance Milera', 'Player', 'tmilera44@hotmail.com', '0421556930', NULL),
  (213, 'Harry Errington', 'Player', 'harry.errington@icloud.com', '0417814639', NULL),
  (214, 'Lochi Nolan', 'Player', 'lochinolan@gmail.com', '0404844359', NULL),
  (215, 'Jake Summerton', 'Player', 'jake.summerton883@schools.sa.edu.au', '0448669155', NULL),
  (216, 'Matthew Coulthard', 'Player', 'mattgc133@gmail.com', '0407858444', NULL),
  (217, 'Brodie Hines', 'Player', 'kadina@sportspower.com.au', '0408082305', NULL),
  (218, 'Baylan Mummery', 'Player', 'tamyka@rocketmail.com', '0401910771', NULL),
  (219, 'Riley Phelan', 'Player', 'dphelan1@gmx.com', '0432182344', NULL),
  (220, 'Ryan Bull', 'Player', 'ryanbull203@gmail.com', '0499977065', NULL),
  (221, 'Brodie Platten', 'Player', 'shaunplatten17@gmail.com', '0474174246', NULL),
  (222, 'Kai Rankine', 'Player', 'kairankine@gmail.com', '0421897268', NULL),
  (223, 'Riley Beech', 'Player', 'ccbeech@bigpond.com', '0428820420', NULL),
  (224, 'Farren Finn', 'Player', 'dandafinn@gmail.com', '0428140508', NULL),
  (225, 'Hunter Wellgreen', 'Player', 'liddy.02@hotmail.com', '0499989437', NULL),
  (226, 'Brock Wenman', 'Player', 'wenmo27@bigpond.com', '0459964294', NULL),
  (227, 'Chase Martin', 'Player', 'chasemartin2109@gmail.com', '0488332027', NULL),
  (228, 'Ryan Plumb', 'Player', 'rap.cricketbat@hotmail.com', '0429311026', NULL),
  (229, 'Patrick Taylor', 'Player', 'patrick.taylor@y7mail.com', '0430143608', NULL),
  (230, 'Dylan Niotis', 'Player', 'jniotis@bigpond.com', '0417818943', NULL),
  (231, 'Isaac Elliot', 'Player', 'isaacjelliott99@gmail.com', '0408862405', NULL),
  (232, 'Jack Leighton', 'Player', 'jack.leighton1298@gmail.com', '0407185088', NULL),
  (233, 'Izaak Hann', 'Player', 'izaakhann@hotmail.com', '0439856728', NULL),
  (234, 'Matthew Rankine', 'Player', 'matt.rankine@hotmail.com', '0401762738', NULL),
  (235, 'Zak Cuthill', 'Player', 'zakcuthill33@gmail.com', '0421396058', NULL),
  (236, 'Corey White', 'Player', 'coreywhite1611hotmail.com', '0459207962', NULL),
  (237, 'Rivva Karpany', 'Player', 'cmob789@icloud.com', '0438770906', NULL),
  (238, 'Ben Dunk', 'Player', 'dunkben@ymail.com', '0419000426', NULL),
  (239, 'Jesse May', 'Player', 'jessemay171@gmail.com', '0434466249', NULL),
  (240, 'Todd Summerton', 'Player', 'toddsummo@gmail.com', '0448230002', NULL),
  (241, 'Tyson Gray', 'Player', 'tyson.gray8@outlook.com', '0466564736', NULL),
  (242, 'Cohen Mummery', 'Player', 'tamyka@rocketmail.com', '0401910771', NULL),
  (243, 'Glenn Bretten', 'Player', 'glenn.bretten@bigpond.com', '0419191369', NULL),
  (244, 'Zacquari Graham', 'Player', 'zgraham571@gmail.com', '0413267419', NULL),
  (245, 'Luke Russel', 'Player', 'lisaandrusty@hotmail.com', '0483855504', NULL),
  (246, 'Josh Bull', 'Player', 'lizberger70@gmail.com', '0409289622', NULL),
  (247, 'Luke Webb', 'Player', 'lukey_webb@hotmail.com', '0487997250', NULL),
  (248, 'Thomas Errington', 'Player', 'thomas.errington@outlook.com', '0448855187', NULL),
  (249, 'Michael Bersagilere', 'Player', 'ianjeery@gmail.com', '0420445726', NULL),
  (250, 'Steve McDonald Electrical', 'Bronze Sposnsors', 'smelecaccs@outlook.com', NULL, NULL),
  (251, 'NRG Electrical', 'VIP', 'admin@enrgs.com', NULL, NULL),
  (252, 'Paul Van Da Haak', 'Bronze Sposnsors', 'paulvdh0@telstra.com', '0414507719', NULL),
  (253, 'Thomas Depledge', 'Bronze Parton', NULL, NULL, NULL),
  (254, 'Guns & Buns', 'Gold Sponsor', NULL, NULL, NULL),
  (255, 'Shippys Hardware', 'Gold Sponsor', NULL, NULL, NULL),
  (256, 'Kadina Mitre 10', 'Club Sponsor', NULL, NULL, NULL),
  (257, 'Kadina Aluminimum', 'Bronze', 'sales.kap@outlook.com', NULL, NULL),
  (258, 'Miriam Errington Conveyancing', 'Bronze', 'miriam@meconvey.com.au', NULL, NULL),
  (259, 'Yorkes Meats & Small Goods', 'Club', NULL, NULL, NULL),
  (260, 'Aw Vater', 'Club', 'info@awvater.com.au', NULL, NULL),
  (261, 'Summerton Construction', 'Silver Sponsors', 'toddsummo@gmail.com', NULL, NULL),
  (262, 'Barossa Mitre 10', 'Bronze Sposnsors', 'ssmith@barossa.coop', NULL, NULL),
  (263, 'Aspen', 'Major Sponsor', 'charlied@aspengroup.com.au', NULL, NULL),
  (264, 'Real Estate on Yorke', 'Gold Sponsor', NULL, NULL, NULL),
  (265, 'Poona Crushing & Gravel', 'Gold Sponsor', NULL, NULL, NULL),
  (266, 'Copper Coast Dental', 'Silver Sponsors', NULL, NULL, NULL),
  (267, 'Elders', 'Bronze Sposnsors', 'steve.larsson@eiua.com.au', NULL, NULL),
  (268, 'KP Lawyers', 'Bronze Sposnsors', NULL, NULL, NULL),
  (269, 'YP Recyling', 'Bronze Sposnsors', NULL, NULL, NULL),
  (270, 'YP Energy', 'Bronze Sposnsors', NULL, NULL, NULL),
  (271, 'Butch''s Auto Detailing', 'Club Sponsor', NULL, NULL, NULL),
  (272, 'Murphy Crash Repaiers', 'Club Sponsor', 'murpcr@bigpond.net.au', NULL, NULL),
  (273, 'Geoff James Paving', 'Club Sponsor', NULL, NULL, NULL),
  (274, 'Copper Coast Dental', 'Silver Sponsors', NULL, NULL, NULL),
  (275, 'Poona Crushing & Gravel', 'Gold Sponsor', NULL, NULL, NULL),
  (276, 'Poona Crushing & Gravel', 'Gold Sponsor', NULL, NULL, NULL),
  (277, 'Real Estate on Yorke', 'Gold Sponsor', NULL, NULL, NULL),
  (278, 'Real Estate on Yorke', 'Gold Sponsor', NULL, NULL, NULL),
  (279, 'Aspen', 'Major Sponsor', 'charlied@aspengroup.com.au', NULL, NULL),
  (280, 'Aspen', 'Major Sponsor', 'charlied@aspengroup.com.au', NULL, NULL),
  (281, 'Shippys Hardware', 'Gold Sponsor', NULL, NULL, NULL),
  (282, 'Summerton Construction', 'Silver Sponsors', 'toddsummo@gmail.com', NULL, NULL),
  (283, 'NRG Electrical', 'VIP', 'admin@enrgs.com', NULL, NULL),
  (284, 'NRG Electrical', 'VIP', 'admin@enrgs.com', NULL, NULL),
  (285, 'NRG Electrical', 'VIP', 'admin@enrgs.com', NULL, NULL),
  (286, 'Vicki', 'Social Member', 'mousy57@bigpond.com', '0497507719', NULL),
  (287, 'Andy West', 'Silver Parton', 'awest1@bigpond.net.au', '0418859646', NULL),
  (288, 'Get Laid YP', 'Gold Sponsor', 'Getlaidadelaideflooring@gmail.com', NULL, '314 Cornish Terrace,  Wallaroo,SA, 5556'),
  (289, 'Get Laid YP', 'Gold Sponsor', 'Getlaidadelaideflooring@gmail.com', NULL, '314 Cornish Terrace,  Wallaroo,SA, 5556'),
  (290, 'Anthony Paxton', 'Player', 'r.paxton@bigpond.com', '0400 031 019', 'Po Box 271, Wallaroo, SA, 5556'),
  (291, 'Dylan Westlake', 'Player', 'dylanwesty@yahoo.com', '0448 685 033', '4 Harding St, North Beach, 5556,SA'),
  (292, 'Andrew Marshall', 'Player', 'andrew.john.marshall72@hotmail.com', '0427 512 758', NULL),
  (293, 'James Errington', 'Player', 'jim.errington@icloud.com', NULL, NULL),
  (294, 'Mitchell Miller', 'Player', 'shannonmiller5@bigpond.com', NULL, NULL),
  (295, 'St Mary Mackillop', 'Gold Sponsor', 'finance@stmm.catholic.edu.au', '88215800', NULL),
  (296, 'Keith Penhall', 'Social Member', NULL, NULL, NULL),
  (297, 'Get Laid YP', 'Gold Sponsor', 'Getlaidadelaideflooring@gmail.com', NULL, '314 Cornish Terrace,  Wallaroo,SA, 5556'),
  (298, 'Shippys Hardware', 'Gold Sponsor', NULL, NULL, NULL),
  (299, 'Paul Shepard', 'Social Member', NULL, NULL, NULL),
  (300, 'Kevin Davies', 'Social Member', NULL, NULL, NULL),
  (301, 'Williams Tint s and Glass', 'Bronze Sponsor', 'williamstintsandglass@gmail.com', NULL, NULL),
  (302, 'CME Roofing', 'Gold Sponsor', 'dmilla55@hotmail.com', NULL, NULL),
  (303, 'CME Roofing', 'Gold Sponsor', 'dmilla55@hotmail.com', NULL, NULL),
  (304, 'CME Roofing', 'Gold Sponsor', 'dmilla55@hotmail.com', NULL, NULL),
  (305, 'Mc Donalds Kadina', 'Bronze Sponsor', 'mark.roberts@au.stores.mcd.com', NULL, NULL),
  (306, 'Rick Grillett', 'Social Member', NULL, NULL, NULL),
  (307, 'Mark Wenham', 'SilverParton', NULL, NULL, NULL),
  (308, 'Guns & Buns', 'Gold Sponsor', NULL, NULL, NULL),
  (309, 'Guns & Buns', 'Gold Sponsor', NULL, NULL, NULL),
  (310, 'Coast to Coast Blinds', 'Bronze Sponsor', NULL, NULL, NULL),
  (311, 'David Flint', 'Social Member', NULL, NULL, NULL),
  (312, 'Natsha Master', 'Bronze Parton', NULL, NULL, NULL),
  (313, 'Copper Coast Gas Supplies', 'Bronze Sposnsors', 'coppercoastgas@gmail.com', NULL, NULL),
  (314, 'CBS Bins', 'Silver Sponsors', NULL, NULL, NULL),
  (315, 'Marina Tavern', 'Gold Sponsor', NULL, NULL, NULL),
  (316, 'Prince Edward Hotel Socail Club', 'Bronze Sponsor', NULL, NULL, NULL),
  (317, NULL, NULL, NULL, NULL, NULL),
  (318, NULL, NULL, NULL, NULL, NULL),
  (319, NULL, NULL, NULL, NULL, NULL),
  (320, NULL, NULL, NULL, NULL, NULL),
  (321, NULL, NULL, NULL, NULL, NULL),
  (322, NULL, NULL, NULL, NULL, NULL),
  (323, NULL, NULL, NULL, NULL, NULL),
  (324, NULL, NULL, NULL, NULL, NULL),
  (325, NULL, NULL, NULL, NULL, NULL),
  (326, NULL, NULL, NULL, NULL, NULL),
  (327, NULL, NULL, NULL, NULL, NULL),
  (328, NULL, NULL, NULL, NULL, NULL),
  (329, NULL, NULL, NULL, NULL, NULL),
  (330, NULL, NULL, NULL, NULL, NULL),
  (331, NULL, NULL, NULL, NULL, NULL),
  (332, NULL, NULL, NULL, NULL, NULL),
  (333, NULL, NULL, NULL, NULL, NULL),
  (334, NULL, NULL, NULL, NULL, NULL),
  (335, NULL, NULL, NULL, NULL, NULL),
  (336, NULL, NULL, NULL, NULL, NULL),
  (337, NULL, NULL, NULL, NULL, NULL),
  (338, NULL, NULL, NULL, NULL, NULL),
  (339, NULL, NULL, NULL, NULL, NULL),
  (340, NULL, NULL, NULL, NULL, NULL),
  (341, NULL, NULL, NULL, NULL, NULL),
  (342, NULL, NULL, NULL, NULL, NULL),
  (343, NULL, NULL, NULL, NULL, NULL),
  (344, NULL, NULL, NULL, NULL, NULL),
  (345, NULL, NULL, NULL, NULL, NULL),
  (346, NULL, NULL, NULL, NULL, NULL),
  (347, NULL, NULL, NULL, NULL, NULL),
  (348, NULL, NULL, NULL, NULL, NULL),
  (349, NULL, NULL, NULL, NULL, NULL),
  (350, NULL, NULL, NULL, NULL, NULL)
on conflict (membership_number) do nothing;

-- Voucher entitlements
insert into public.voucher_entitlements (member_id, count, member_group) select id, 2, '61, 62, 295' from public.club_members where membership_number = 61 on conflict do nothing;
insert into public.voucher_entitlements (member_id, count, member_group) select id, 1, '74' from public.club_members where membership_number = 74 on conflict do nothing;
insert into public.voucher_entitlements (member_id, count, member_group) select id, 2, '90' from public.club_members where membership_number = 90 on conflict do nothing;
insert into public.voucher_entitlements (member_id, count, member_group) select id, 2, '94' from public.club_members where membership_number = 94 on conflict do nothing;
insert into public.voucher_entitlements (member_id, count, member_group) select id, 2, '98' from public.club_members where membership_number = 98 on conflict do nothing;
insert into public.voucher_entitlements (member_id, count, member_group) select id, 2, '104' from public.club_members where membership_number = 104 on conflict do nothing;
insert into public.voucher_entitlements (member_id, count, member_group) select id, 1, '109' from public.club_members where membership_number = 109 on conflict do nothing;
insert into public.voucher_entitlements (member_id, count, member_group) select id, 1, '144' from public.club_members where membership_number = 144 on conflict do nothing;
insert into public.voucher_entitlements (member_id, count, member_group) select id, 2, '147' from public.club_members where membership_number = 147 on conflict do nothing;
insert into public.voucher_entitlements (member_id, count, member_group) select id, 1, '155' from public.club_members where membership_number = 155 on conflict do nothing;
insert into public.voucher_entitlements (member_id, count, member_group) select id, 1, '164' from public.club_members where membership_number = 164 on conflict do nothing;
insert into public.voucher_entitlements (member_id, count, member_group) select id, 2, '167' from public.club_members where membership_number = 167 on conflict do nothing;
insert into public.voucher_entitlements (member_id, count, member_group) select id, 1, '170' from public.club_members where membership_number = 170 on conflict do nothing;
insert into public.voucher_entitlements (member_id, count, member_group) select id, 1, '173' from public.club_members where membership_number = 173 on conflict do nothing;
insert into public.voucher_entitlements (member_id, count, member_group) select id, 1, '176' from public.club_members where membership_number = 176 on conflict do nothing;
insert into public.voucher_entitlements (member_id, count, member_group) select id, 1, '179' from public.club_members where membership_number = 179 on conflict do nothing;
insert into public.voucher_entitlements (member_id, count, member_group) select id, 1, '182' from public.club_members where membership_number = 182 on conflict do nothing;
insert into public.voucher_entitlements (member_id, count, member_group) select id, 1, '207' from public.club_members where membership_number = 207 on conflict do nothing;
insert into public.voucher_entitlements (member_id, count, member_group) select id, 2, '251' from public.club_members where membership_number = 251 on conflict do nothing;
insert into public.voucher_entitlements (member_id, count, member_group) select id, 3, '263' from public.club_members where membership_number = 263 on conflict do nothing;
insert into public.voucher_entitlements (member_id, count, member_group) select id, 1, '275' from public.club_members where membership_number = 275 on conflict do nothing;
insert into public.voucher_entitlements (member_id, count, member_group) select id, 1, '277' from public.club_members where membership_number = 277 on conflict do nothing;
insert into public.voucher_entitlements (member_id, count, member_group) select id, 1, '288' from public.club_members where membership_number = 288 on conflict do nothing;
insert into public.voucher_entitlements (member_id, count, member_group) select id, 2, '138, 139' from public.club_members where membership_number = 138 on conflict do nothing;
insert into public.voucher_entitlements (member_id, count, member_group) select id, 1, '158, 159, 160' from public.club_members where membership_number = 158 on conflict do nothing;
insert into public.voucher_entitlements (member_id, count, member_group) select id, 2, '86, 87, 88, 89' from public.club_members where membership_number = 86 on conflict do nothing;
insert into public.voucher_entitlements (member_id, count, member_group) select id, 1, '161, 162, 163' from public.club_members where membership_number = 161 on conflict do nothing;
insert into public.voucher_entitlements (member_id, count, member_group) select id, 2, '69, 70, 71' from public.club_members where membership_number = 69 on conflict do nothing;
insert into public.voucher_entitlements (member_id, count, member_group) select id, 1, '182, 183, 184' from public.club_members where membership_number = 182 on conflict do nothing;
