// AUTO-GENERATED from !honor boards.xlsx — do not edit by hand

export interface ClassicRow { year:number; president:string; secretary:string; a_captain:string; }
export const CLASSIC_BOARD: ClassicRow[] = [
  { year:1900, president:'A. E. Mueller', secretary:'W. Bryden', a_captain:'J. Herbert' },
  { year:1901, president:'A. E. Mueller', secretary:'W. Bryden', a_captain:'T. Thomas' },
  { year:1902, president:'A. E. Mueller', secretary:'W. Bryden', a_captain:'W. Williams' },
  { year:1903, president:'A. E. Mueller', secretary:'W. Bryden', a_captain:'W. Williams' },
  { year:1904, president:'A. E. Mueller', secretary:'W. Bryden', a_captain:'F. Clayton' },
  { year:1905, president:'Dr. Fulton', secretary:'J. D. Phillips', a_captain:'W. Williams' },
  { year:1906, president:'Dr C. F. C. Wilson', secretary:'W. Bryden', a_captain:'W. Williams' },
  { year:1907, president:'Dr C. F. C. Wilson', secretary:'W. Bryden', a_captain:'T. Thomas' },
  { year:1908, president:'Dr C. F. C. Wilson', secretary:'W. Bryden', a_captain:'T. Thomas' },
  { year:1909, president:'W. Ogilvie', secretary:'W. Bryden', a_captain:'N. Walters' },
  { year:1910, president:'W. Ogilvie', secretary:'W. Bryden', a_captain:'S. Juniper' },
  { year:1911, president:'W. J. Dodge', secretary:'W. Bryden', a_captain:'E. Barnes' },
  { year:1912, president:'W. J. Dodge', secretary:'W. Bryden', a_captain:'E. Barnes' },
  { year:1913, president:'Dr C. F. C. Wilson', secretary:'W. Bryden', a_captain:'F. Pedder' },
  { year:1914, president:'J. F. Herbert', secretary:'W. Bryden', a_captain:'RECESS - War' },
  { year:1915, president:'J. F. Herbert', secretary:'W. Bryden', a_captain:'T. Buck' },
  { year:1916, president:'J. F. Herbert', secretary:'W. Bryden', a_captain:'F. Pedder' },
  { year:1917, president:'J. F. Herbert', secretary:'W. Bryden', a_captain:'J. Pedder' },
  { year:1918, president:'F. W. Birbeck', secretary:'W. Bryden', a_captain:'J. Pedder' },
  { year:1919, president:'F. W. Birbeck', secretary:'W. Bryden', a_captain:'J. Pedder' },
  { year:1920, president:'F. W. Birbeck', secretary:'W. Bryden', a_captain:'J. Pedder' },
  { year:1921, president:'F. W. Birbeck', secretary:'W. Chapman', a_captain:'J. Pedder' },
  { year:1922, president:'F. W. Birbeck', secretary:'W. Bryden', a_captain:'J. Pedder' },
  { year:1923, president:'F. W. Birbeck', secretary:'J. Stanyer', a_captain:'J. Pedder' },
  { year:1924, president:'F. W. Birbeck', secretary:'J. Stanyer', a_captain:'J. Pedder' },
  { year:1925, president:'F. W. Birbeck', secretary:'H. Davies', a_captain:'J. Pedder' },
  { year:1926, president:'F. W. Birbeck', secretary:'R. Young/R. Errington', a_captain:'P. Brown' },
  { year:1927, president:'P. A. Edwards', secretary:'R. Young/W. H. Bennett', a_captain:'B. McLean' },
  { year:1928, president:'P. A. Edwards', secretary:'R. Young/J. Buck', a_captain:'B. McLean' },
  { year:1929, president:'P. A. Edwards', secretary:'R. Young/W. H. Paull', a_captain:'B. McLean' },
  { year:1930, president:'P. A. Edwards', secretary:'F. J. Pengilly', a_captain:'J. Pedder' },
  { year:1931, president:'P. A. Edwards', secretary:'F. J. Pengilly', a_captain:'J. Lukeman' },
  { year:1932, president:'J. Woods', secretary:'H. J. Lee', a_captain:'J. Lukeman' },
  { year:1933, president:'J. Woods', secretary:'J. Heher', a_captain:'S. Kempster' },
  { year:1934, president:'P. A. Edwards', secretary:'O. Cross', a_captain:'S. Kempster/J. Buck' },
  { year:1935, president:'P. A. Edwards', secretary:'O. Cross', a_captain:'S. Kempster/J. Buck' },
  { year:1936, president:'J. Ladner', secretary:'J. Ladner', a_captain:'J. Lukeman' },
  { year:1937, president:'P. A. Edwards', secretary:'F. J. Pengilly', a_captain:'J. Buck' },
  { year:1938, president:'P. A. Edwards', secretary:'E. S. Ware', a_captain:'J. Lukeman' },
  { year:1939, president:'P. A. Edwards', secretary:'E. S. Ware', a_captain:'M. Fielder' },
  { year:1940, president:'P. A. Edwards', secretary:'E. S. Ware', a_captain:'M. Fielder' },
  { year:1941, president:'P. A. Edwards', secretary:'E. S. Ware', a_captain:'RECESS - War' },
  { year:1942, president:'RECESS - War', secretary:'RECESS - War', a_captain:'RECESS - War' },
  { year:1943, president:'RECESS - War', secretary:'RECESS - War', a_captain:'RECESS - War' },
  { year:1944, president:'RECESS - War', secretary:'RECESS - War', a_captain:'RECESS - War' },
  { year:1945, president:'P. A. Edwards', secretary:'E. Buck', a_captain:'J. Buck' },
  { year:1946, president:'G. L. Boase', secretary:'E. Buck', a_captain:'J. Buck' },
  { year:1947, president:'G. L. Boase', secretary:'H. L. Hopkins', a_captain:'M. Boyce' },
  { year:1948, president:'G. L. Boase', secretary:'H. L. Hopkins', a_captain:'L. T. Evans' },
  { year:1949, president:'G. L. Boase', secretary:'H. L. Hopkins', a_captain:'C. Bowman' },
  { year:1950, president:'W. H. Paull', secretary:'R. J. Buck', a_captain:'R. L. Broadstock' },
  { year:1951, president:'W. H. Paull', secretary:'H. L. Hopkins', a_captain:'R. L. Broadstock' },
  { year:1952, president:'W. H. Paull', secretary:'R. J. Buck', a_captain:'R. J. Simpson' },
  { year:1953, president:'W. H. Paull', secretary:'H. L. Hopkins', a_captain:'E. C. Simpson' },
  { year:1954, president:'W. H. Paull', secretary:'E. Buck', a_captain:'E. C. Simpson' },
  { year:1955, president:'H. R. Woodforde', secretary:'E. Buck', a_captain:'L. T. Evans' },
  { year:1956, president:'H. R. Woodforde', secretary:'E. Buck', a_captain:'L. T. Evans' },
  { year:1957, president:'H. R. Woodforde', secretary:'E. Buck', a_captain:'L. T. Evans' },
  { year:1958, president:'H. R. Woodforde', secretary:'H. L. Hopkins/K. Kerslake', a_captain:'R. E. Ross' },
  { year:1959, president:'H. R. Woodforde', secretary:'T. G. Gooley/G. Haylock', a_captain:'M. McCabe' },
  { year:1960, president:'H. R. Woodforde', secretary:'C. G. Haylock', a_captain:'L. T. Evans' },
  { year:1961, president:'H. R. Woodforde', secretary:'W. J. McLean', a_captain:'E. C. Simpson' },
  { year:1962, president:'L. T. Evans', secretary:'V. Kelley', a_captain:'D. Percy' },
  { year:1963, president:'L. T. Evans', secretary:'V. Kelley', a_captain:'D. K. Thomas' },
  { year:1964, president:'L. T. Evans', secretary:'E. Buck', a_captain:'W. Avery' },
  { year:1965, president:'L. T. Evans', secretary:'E. Buck', a_captain:'R. Thomas' },
  { year:1966, president:'L. T. Evans', secretary:'D. R. Shaw', a_captain:'G. Barker' },
  { year:1967, president:'L. T. Evans', secretary:'D. R. Shaw', a_captain:'G. Barker' },
  { year:1968, president:'L. T. Evans', secretary:'D. R. Shaw', a_captain:'R. K. Ryles' },
  { year:1969, president:'L. T. Evans', secretary:'R. K. Ryles', a_captain:'N. Phillips' },
];

export interface ExpandedRow {
  year:number; president:string; secretary:string; treasurer:string;
  a_coach:string; a_captain:string; a_bf:string; a_goals:string;
  b_coach:string; b_captain:string; b_bf:string; b_goals:string;
  frank:string; bowman:string;
}
export const EXPANDED_BOARD: ExpandedRow[] = [
  { year:1970, president:'L. T. Evans', secretary:'R. K. Ryles', treasurer:'', a_coach:'L. T. Evans', a_captain:'D. R. Hibbard', a_bf:'B. Cronin', a_goals:'G.Oliver', b_coach:'', b_captain:'D. Shaw', b_bf:'K. Pope', b_goals:'', frank:'', bowman:'' },
  { year:1971, president:'S. M. Mellow', secretary:'R. K. Ryles', treasurer:'', a_coach:'L. T. Evans', a_captain:'D. R. Hibbard', a_bf:'', a_goals:'', b_coach:'', b_captain:'', b_bf:'K. Pope', b_goals:'', frank:'', bowman:'' },
  { year:1972, president:'S. M. Mellow', secretary:'R. K. Ryles', treasurer:'', a_coach:'L. T. Evans', a_captain:'N. Kinglsey', a_bf:'N. Tobin', a_goals:'', b_coach:'', b_captain:'', b_bf:'G. Chittleborough', b_goals:'', frank:'', bowman:'' },
  { year:1973, president:'S. M. Mellow', secretary:'R. K. Ryles', treasurer:'', a_coach:'L. T. Evans', a_captain:'P. Willum', a_bf:'', a_goals:'', b_coach:'', b_captain:'', b_bf:'', b_goals:'', frank:'', bowman:'' },
  { year:1974, president:'G. Grillett', secretary:'K. O\'Shea', treasurer:'', a_coach:'L. T. Evans', a_captain:'G. Oliver', a_bf:'I. Thomas', a_goals:'', b_coach:'', b_captain:'', b_bf:'', b_goals:'', frank:'', bowman:'' },
  { year:1975, president:'G. Grillett', secretary:'D. R. Hann', treasurer:'', a_coach:'L. T. Evans', a_captain:'G. Oliver', a_bf:'', a_goals:'R. Newhousen', b_coach:'', b_captain:'', b_bf:'D. C. Westlake', b_goals:'', frank:'', bowman:'G. R. Borlace' },
  { year:1976, president:'G. Grillett', secretary:'D. R. Hann', treasurer:'M. Pratt', a_coach:'J. Ryan', a_captain:'J. Ryan', a_bf:'G. Borlace', a_goals:'R. Newhousen', b_coach:'', b_captain:'D. C. Westlake', b_bf:'G. Chittleborough', b_goals:'', frank:'', bowman:'S. D. Hann' },
  { year:1977, president:'L. T. Evans', secretary:'D. R. Hann', treasurer:'', a_coach:'J. Ryan', a_captain:'J. Ryan', a_bf:'', a_goals:'R. Newhousen', b_coach:'', b_captain:'', b_bf:'', b_goals:'', frank:'', bowman:'D. J. Martin' },
  { year:1978, president:'L. T. Evans', secretary:'D. R. Hann', treasurer:'', a_coach:'J. Ryan', a_captain:'G. Simpson', a_bf:'', a_goals:'R. Newhousen', b_coach:'', b_captain:'', b_bf:'D. C. Westlake', b_goals:'', frank:'', bowman:'A. E. Boys' },
  { year:1979, president:'F. E. Hopkins', secretary:'D. R. Hann', treasurer:'', a_coach:'D. Karger', a_captain:'P. Willment', a_bf:'J. Boys', a_goals:'R. Newhousen', b_coach:'', b_captain:'', b_bf:'B. G. Daniel', b_goals:'', frank:'', bowman:'K. P. Flint' },
  { year:1980, president:'F. E. Hopkins', secretary:'D. R. Hann', treasurer:'', a_coach:'D. Karger', a_captain:'P. Willment', a_bf:'', a_goals:'', b_coach:'', b_captain:'', b_bf:'D. C. Westlake', b_goals:'', frank:'', bowman:'K. P. Flint' },
  { year:1981, president:'F. E. Hopkins', secretary:'D. R. Hann', treasurer:'B. Kneebone', a_coach:'R. Newhousen', a_captain:'B. Hann', a_bf:'G. SImpson', a_goals:'K. Penney', b_coach:'', b_captain:'R. Simpson', b_bf:'G. Maddison', b_goals:'J. Lanyon', frank:'', bowman:'A. J. Coppen' },
  { year:1982, president:'F. E. Hopkins', secretary:'D. R. Hann', treasurer:'B. Kneebone', a_coach:'R. Newhousen', a_captain:'J. Cass', a_bf:'', a_goals:'K. Penney', b_coach:'G. Maddison', b_captain:'G. Oliver', b_bf:'Dean Smith', b_goals:'J. Lanyon', frank:'G. Simpson', bowman:'A. J. Coppen' },
  { year:1983, president:'F. E. Hopkins', secretary:'D. R. Hann', treasurer:'B. Kneebone', a_coach:'I. Westbrook', a_captain:'I. Westbrook', a_bf:'A. Ladner', a_goals:'R. E. Higgins', b_coach:'', b_captain:'', b_bf:'A. Coppen', b_goals:'J. Lanyon', frank:'J. Westbrook', bowman:'S. P. Scholes' },
  { year:1984, president:'F. E. Hopkins', secretary:'D. R. Hann', treasurer:'', a_coach:'I. Westbrook', a_captain:'I. Westbrook', a_bf:'I. Westbrook', a_goals:'R. E. Higgins', b_coach:'', b_captain:'', b_bf:'G. Borlace', b_goals:'M. C. Borlace', frank:'R. Higgins', bowman:'A. J. Ladner' },
  { year:1985, president:'F. E. Hopkins', secretary:'T. Bauerochse', treasurer:'', a_coach:'G. Jarman', a_captain:'G. Jarman', a_bf:'A. Ladner', a_goals:'R. E. Higgins', b_coach:'G. Borlace', b_captain:'B. G. Daniel', b_bf:'Dean Smith', b_goals:'', frank:'M. Newhousen', bowman:'M. C. Scholes' },
  { year:1986, president:'F. E. Hopkins', secretary:'T. Bauerochse', treasurer:'G. Tasker', a_coach:'G. Jarman', a_captain:'G. Jarman', a_bf:'D. Flint', a_goals:'R. E. Higgins', b_coach:'', b_captain:'', b_bf:'A. Coppen', b_goals:'', frank:'', bowman:'I. C. Shields' },
  { year:1987, president:'L. T. Evans', secretary:'R. Loader', treasurer:'G. Tasker', a_coach:'P. Willment', a_captain:'K. Penney', a_bf:'G. Jarman', a_goals:'K. Penney', b_coach:'', b_captain:'', b_bf:'B. Smith/M. Dalby', b_goals:'', frank:'C. Chittleborough', bowman:'I. L. Harris' },
  { year:1988, president:'T. Bauerochse', secretary:'R. Loader', treasurer:'G. Tasker', a_coach:'T. White', a_captain:'T. White', a_bf:'I. Woods', a_goals:'K. Penney', b_coach:'', b_captain:'', b_bf:'B. Borlace', b_goals:'', frank:'G. Jarman', bowman:'I. Woods' },
  { year:1989, president:'L. C. Griffits', secretary:'P. Brand', treasurer:'G. Tasker', a_coach:'T. White', a_captain:'K. Penney', a_bf:'D. Thomson', a_goals:'K. Penney', b_coach:'D. Westlake', b_captain:'', b_bf:'B. G. Daniel', b_goals:'', frank:'T. Bown', bowman:'M. Rayner/I. Woods/D. T. Page' },
  { year:1990, president:'L. L. Johns', secretary:'A. W. Peters', treasurer:'G. Tasker', a_coach:'R. E. Higgins', a_captain:'R. E. Higgins', a_bf:'D. R. Price', a_goals:'R. E. Higgins', b_coach:'R. Day', b_captain:'B. G. Daniel', b_bf:'R. Green', b_goals:'S. Slee', frank:'L. L. Johns', bowman:'C. N. Johns' },
  { year:1991, president:'L. L. Johns', secretary:'A. W. Peters', treasurer:'G. Tasker', a_coach:'R. E. Higgins', a_captain:'R. E. Higgins', a_bf:'B. Kennedy', a_goals:'K. Penney', b_coach:'', b_captain:'B. G. Daniel', b_bf:'D. Liddy', b_goals:'J. Price', frank:'K. G. Daniel', bowman:'D. T. Page' },
  { year:1992, president:'L. L. Johns', secretary:'A. W. Peters', treasurer:'G. Tasker', a_coach:'R. E. Higgins', a_captain:'R. E. Higgins', a_bf:'K. Flint', a_goals:'R. E. Higgins', b_coach:'', b_captain:'S. A. Grillett', b_bf:'S. Slee', b_goals:'T. White', frank:'R. Newhousen', bowman:'D. T. Page' },
  { year:1993, president:'B. G. Daniel', secretary:'A. W. Peters', treasurer:'G. Tasker', a_coach:'L. G. Pearce', a_captain:'L. G. Pearce', a_bf:'M. Daniel', a_goals:'L. G. Pearce', b_coach:'', b_captain:'D. Flint', b_bf:'D. G. Murphy', b_goals:'S. Slee', frank:'M. Newhousen', bowman:'J. P. Chittleborough' },
  { year:1994, president:'L. L. Johns', secretary:'A. W. Peters', treasurer:'G. Tasker', a_coach:'L. G. Pearce', a_captain:'L. G. Pearce', a_bf:'M. Daniel', a_goals:'S. Taylor', b_coach:'', b_captain:'S. A. Grillett', b_bf:'K. L. Collins', b_goals:'S. Adams', frank:'J. A. Johns', bowman:'S. R. Adams' },
  { year:1995, president:'L. L. Johns', secretary:'A. W. Peters', treasurer:'G. Tasker', a_coach:'L. G. Pearce', a_captain:'M. P. Daniel', a_bf:'J. Wilkinson', a_goals:'G. James', b_coach:'D. R. Price', b_captain:'', b_bf:'K. L. Collins', b_goals:'R. Rawlings', frank:'J. Penhall', bowman:'S. R. Adams / R. Depledge' },
  { year:1996, president:'L. L. Johns', secretary:'A. W. Peters', treasurer:'G. Tasker', a_coach:'P. Arnall', a_captain:'C. N. Johns/M. P. Daniel/G. James', a_bf:'G. James', a_goals:'G. James', b_coach:'D. R. Price', b_captain:'P. S. Boundy', b_bf:'K. L. Collins', b_goals:'J. Hage', frank:'B. Smith', bowman:'S. A. Dohnt' },
  { year:1997, president:'L. L. Johns', secretary:'A. W. Peters', treasurer:'G. Tasker', a_coach:'P. Arnall', a_captain:'C. N. Johns/M. P. Daniel/G. James', a_bf:'M. Daniel', a_goals:'G. James', b_coach:'D. Owen', b_captain:'D. C. Smith', b_bf:'B. F. Page', b_goals:'J. Hage', frank:'P. Arnell', bowman:'S. A. Dohnt' },
  { year:1998, president:'L. L. Johns', secretary:'A. W. Peters', treasurer:'G. Tasker', a_coach:'M. P. Daniel', a_captain:'M. P. Daniel', a_bf:'M. Daniel', a_goals:'G. James', b_coach:'G. Oliver', b_captain:'D. C. Smith', b_bf:'K. L. Collins', b_goals:'J. Hage', frank:'K. L. Collins', bowman:'S. R. Adams' },
  { year:1999, president:'L. L. Johns', secretary:'A. W. Peters', treasurer:'G. Tasker', a_coach:'T. Williams', a_captain:'C. N. Johns', a_bf:'D. R. Price', a_goals:'A. Crack', b_coach:'', b_captain:'', b_bf:'P. S. Boundy', b_goals:'D. C.  Smith', frank:'L. W. Johns', bowman:'O. J. Page' },
  { year:2000, president:'K. R. Penhall', secretary:'A. W. Peters', treasurer:'G. Tasker', a_coach:'T. Williams', a_captain:'C. N. Johns', a_bf:'M. Jeffries', a_goals:'A. Crack', b_coach:'D. R. Price', b_captain:'', b_bf:'R. Winning', b_goals:'D. C. Smith', frank:'S. McInerney', bowman:'not awarded' },
  { year:2001, president:'K. R. Penhall', secretary:'B. J. Rowe', treasurer:'G. Tasker', a_coach:'C. Kellett', a_captain:'S. A. Dohnt', a_bf:'C. Mansell', a_goals:'G. James', b_coach:'R. Ling', b_captain:'', b_bf:'B. Boundy', b_goals:'A. Barnes', frank:'J. Penhall / M. Newhousen', bowman:'O. J. Page' },
  { year:2002, president:'A. W. Peters', secretary:'B. J. Rowe', treasurer:'G. Tasker', a_coach:'G. James', a_captain:'G. James/S. A. Dohnt', a_bf:'S. C. Dunstan', a_goals:'G. James', b_coach:'K. L. Collins', b_captain:'K. L. Collins', b_bf:'K. L. Collins/G. Gurner', b_goals:'B. Bateson', frank:'D. Miller', bowman:'R. D. Page' },
  { year:2003, president:'L. W. Johns', secretary:'B. J. Rowe', treasurer:'G. Tasker', a_coach:'G. James', a_captain:'G. R. Willment', a_bf:'S. C. Dunstan', a_goals:'G. James', b_coach:'K. L. Collins', b_captain:'K. L. Collins', b_bf:'K. L. Collins/S. Jamieson', b_goals:'B. Bateson', frank:'G. J. Cooper', bowman:'not awarded' },
  { year:2004, president:'L. W. Johns', secretary:'W. R. Discombe', treasurer:'R. Newhousen / R. Egbert', a_coach:'T. Winning', a_captain:'D. S. Duncan', a_bf:'S. C. Dunstan', a_goals:'G. James', b_coach:'', b_captain:'P. S. Boundy', b_bf:'B. J. Stewart', b_goals:'D. C. Smith', frank:'K. Willum / J. Chittleborough', bowman:'not awarded' },
  { year:2005, president:'L. W. Johns', secretary:'W. R. Discombe', treasurer:'M. Depledge', a_coach:'T. Winning', a_captain:'M. I. Rayner', a_bf:'S. Broad', a_goals:'N. Flynn', b_coach:'', b_captain:'B. J. Stewart/P. S. Boundy', b_bf:'S. Donald', b_goals:'D. Giles', frank:'C. Chittleborough', bowman:'S. D. Beaney' },
  { year:2006, president:'L. W. Johns', secretary:'S. P. Hamdorf', treasurer:'M. Depledge', a_coach:'D. Page', a_captain:'M. I. Rayner', a_bf:'S. C. Dunstan', a_goals:'D. Penney', b_coach:'', b_captain:'K. L. Collins', b_bf:'G. James/S. Donald', b_goals:'G. James', frank:'D. G. Murphy', bowman:'not awarded' },
  { year:2007, president:'K. R. Penhall', secretary:'D. G. Murphy', treasurer:'M. Depledge', a_coach:'D. Page', a_captain:'S. C. Dunstan', a_bf:'R. D. Page', a_goals:'D. Penney', b_coach:'B. J. Stewart', b_captain:'P. Manual', b_bf:'G. James', b_goals:'G. James', frank:'W. Witt', bowman:'A. A. Whittaker' },
  { year:2008, president:'K. P. Flint', secretary:'D. G. Murphy', treasurer:'M. Depledge', a_coach:'D. Page', a_captain:'S. C. Dunstan', a_bf:'S. C. Dunstan', a_goals:'K. Williams', b_coach:'S. A. Grillett', b_captain:'D. Duncan', b_bf:'B. Meier', b_goals:'G. James', frank:'G. Tasker', bowman:'N. B. Murphy / G. B. Bretten' },
  { year:2009, president:'K. P. Flint', secretary:'D. G. Murphy', treasurer:'M. Depledge', a_coach:'S. Dunstan', a_captain:'B. A. Cuthill', a_bf:'G. Bretten', a_goals:'K. Williams', b_coach:'S. A. Grillett', b_captain:'M. Pearce', b_bf:'C. Scott', b_goals:'G. James', frank:'L. C. Griffits', bowman:'B. J. Abela' },
  { year:2010, president:'D. C. Westlake', secretary:'D. G. Murphy', treasurer:'M. Depledge', a_coach:'C. Chittleborough / D. Duncan', a_captain:'B. A. Cuthill/S. D. Miller', a_bf:'B. Abela', a_goals:'B. Pearce', b_coach:'S. A. Grillett', b_captain:'B. F. Page', b_bf:'B. F. Page', b_goals:'G. James', frank:'S. A. Grillett', bowman:'J. G. Summerton' },
  { year:2011, president:'D. C. Westlake', secretary:'D. G. Murphy', treasurer:'M. Depledge', a_coach:'C. Chittleborough / D. Duncan', a_captain:'R. D. Page/M. W. Grillett', a_bf:'S. Green', a_goals:'A. Ross', b_coach:'S. A. Grillett', b_captain:'', b_bf:'S. C. Dunstan', b_goals:'M. Bodie', frank:'R. Grillett', bowman:'D. L. Boundy' },
  { year:2012, president:'D. K. Page', secretary:'D. G. Murphy', treasurer:'M. Depledge', a_coach:'R. Nelson', a_captain:'R. D. Page/M. W. Grillett', a_bf:'R. D. Page', a_goals:'D. Francis', b_coach:'G. James', b_captain:'R. J. Hall', b_bf:'R. J. Hall', b_goals:'M. Bodie', frank:'S. Weger', bowman:'L. D. Hann' },
  { year:2013, president:'M. C. Borlace', secretary:'D. G. Murphy', treasurer:'M. Depledge', a_coach:'R. Nelson', a_captain:'R. D. Page/M. W. Grillett', a_bf:'N. Wright', a_goals:'A. Ross', b_coach:'R. Carrick', b_captain:'T. Nadich/N. Collins', b_bf:'T. Nadich', b_goals:'G. James', frank:'R. Westlake', bowman:'R. M. Westlake' },
  { year:2014, president:'M. C. Borlace', secretary:'D. G. Murphy', treasurer:'M. Depledge', a_coach:'R. Nelson', a_captain:'M. W. Grillett', a_bf:'D. S. Westlake', a_goals:'A. Ross', b_coach:'D. R. Price', b_captain:'T. Nadich', b_bf:'J. Errington', b_goals:'J. Weight', frank:'P. Haylock', bowman:'R. M. Westlake' },
  { year:2015, president:'M. C. Borlace', secretary:'A. R. Elliott', treasurer:'M. Depledge', a_coach:'R. Nelson', a_captain:'M. W. Grillett', a_bf:'L. Carey', a_goals:'C. McLean', b_coach:'D. R. Price', b_captain:'T. Nadich', b_bf:'T. Nadich', b_goals:'M. Bodie', frank:'G. D. Klingner', bowman:'R. M. Westlake' },
  { year:2016, president:'C. N. Johns', secretary:'S. C. Tappin', treasurer:'M. Depledge', a_coach:'J. Yeates', a_captain:'N. B. Murphy', a_bf:'R. Westlake', a_goals:'J. Bollmeyer', b_coach:'D. R. Price', b_captain:'D. Besselaar', b_bf:'D. Besselaar', b_goals:'T. Grillett', frank:'M. Depledge', bowman:'R. M. Westlake' },
  { year:2017, president:'C. N. Johns', secretary:'S. C. Tappin', treasurer:'M. Depledge', a_coach:'J. Yeates', a_captain:'N. B. Murphy/R. Westlake/L. Harder', a_bf:'B. Ellis', a_goals:'R. Westlake', b_coach:'S. A. Grillett', b_captain:'T. Nadich', b_bf:'J. May', b_goals:'M. Bodie', frank:'D. Weger', bowman:'B. R. Hann' },
  { year:2018, president:'C. N. Johns', secretary:'J. A. Errington', treasurer:'M. Depledge', a_coach:'D. Cutting', a_captain:'N. B. Murphy', a_bf:'S. Jordan', a_goals:'D. Cutting', b_coach:'S. A. Grillett', b_captain:'T. Nadich', b_bf:'J. Owen', b_goals:'M. Bodie', frank:'A. West', bowman:'J. May' },
  { year:2019, president:'C. N. Johns', secretary:'J. A. Errington', treasurer:'E. Nolan', a_coach:'D. Cutting', a_captain:'N. B. Murphy', a_bf:'B. Russell', a_goals:'D. Cutting', b_coach:'T. Nadich', b_captain:'T. Nadich/T.Summerton', b_bf:'M. W. Grillett', b_goals:'M. Bodie', frank:'C. N. Johns', bowman:'B. R. Hann' },
  { year:2020, president:'J. Russel', secretary:'J. A. Errington', treasurer:'E. Nolan', a_coach:'D. Cutting / B. Abela', a_captain:'Colts Only (Plague)', a_bf:'Colts Only', a_goals:'Colts Only', b_coach:'T. Nadich', b_captain:'Colts Only', b_bf:'Colts Only', b_goals:'Colts Only', frank:'not awarded', bowman:'Colts Only' },
  { year:2021, president:'A. West', secretary:'J. A. Errington', treasurer:'M. Depledge', a_coach:'B. Abela', a_captain:'N. B. Murphy', a_bf:'B. Russell', a_goals:'S. Dyer', b_coach:'P. Manual', b_captain:'T. Errington', b_bf:'S. Miller', b_goals:'R. Walton', frank:'M. Newhousen', bowman:'J. Wharton' },
  { year:2022, president:'A. West', secretary:'J. A. Errington', treasurer:'M. Depledge', a_coach:'B. Abela', a_captain:'N. B. Murphy', a_bf:'B. Russell', a_goals:'C. Martin', b_coach:'P. Manual', b_captain:'T. Summerton', b_bf:'J. Holman', b_goals:'J. Trott', frank:'P. Northeast', bowman:'not awarded' },
  { year:2023, president:'T. Nolan', secretary:'A. West', treasurer:'S. Steer', a_coach:'Cor. Smelt', a_captain:'D. S. Westlake', a_bf:'D. S. Westlake', a_goals:'Con. Smelt', b_coach:'D. Duncan', b_captain:'T. Nadich/L. Hann', b_bf:'L. Faint', b_goals:'L. Faint', frank:'T. R. Depledge', bowman:'R. J. Smelt' },
  { year:2024, president:'T. Nolan', secretary:'T. R. Depledge', treasurer:'S. Steer', a_coach:'Cor. Smelt', a_captain:'D. S. Westlake', a_bf:'T. Grillett', a_goals:'Con. Smelt', b_coach:'D. Duncan', b_captain:'L. Hann/J.Errington', b_bf:'G. Bretten', b_goals:'T. Kay', frank:'D. Marner', bowman:'J. K. Hunter-Price' },
  { year:2025, president:'T. Nolan', secretary:'T. R. Depledge', treasurer:'S. Thomson', a_coach:'R. Depledge (resigned), A. Dekort', a_captain:'H. Errington', a_bf:'Z. Cuthill', a_goals:'T. Luck', b_coach:'J. Yeates', b_captain:'J. Errington', b_bf:'T. Summerton', b_goals:'T. Kay / J. Kelly', frank:'A. Dekort', bowman:'' },
  { year:2026, president:'J. Niotis', secretary:'T. R. Depledge', treasurer:'S. Thomson', a_coach:'M. Rankine', a_captain:'H. Errington/C. Martin', a_bf:'', a_goals:'', b_coach:'J. Yeates', b_captain:'T. Summerton', b_bf:'', b_goals:'', frank:'', bowman:'' },
];

export interface MailMedal { year:number; winner:string; grade:string; }
export const MAIL_MEDALS: MailMedal[] = [
  { year:1892, winner:'H. Kempster', grade:'WFC First Team' },
  { year:1894, winner:'J. Thomas', grade:'WFC First Team' },
  { year:1925, winner:'J. Hopkins', grade:'WFC First Team' },
  { year:1926, winner:'D. Lawson', grade:'WFC First Team' },
  { year:1929, winner:'J. Graham', grade:'WFC First Team' },
  { year:1931, winner:'J. Lukeman', grade:'WFC First Team' },
  { year:1935, winner:'B. Lander', grade:'WFC First Team' },
  { year:1937, winner:'B. Lander', grade:'WFC First Team' },
  { year:1938, winner:'B. Lander', grade:'WFC First Team' },
  { year:1939, winner:'B. Lander', grade:'WFC First Team' },
  { year:1940, winner:'M. Fielder', grade:'WFC First Team' },
  { year:1952, winner:'C. Green', grade:'WFC First Team' },
  { year:1953, winner:'J. Emes', grade:'WFC First Team' },
  { year:1956, winner:'H. J. Smith', grade:'WFC First Team' },
  { year:1966, winner:'Graham Smith', grade:'Senior Colts' },
  { year:1967, winner:'Graham Smith', grade:'Senior Colts' },
  { year:1967, winner:'Norm Phillips', grade:'B Grade' },
  { year:1968, winner:'Peter Mildren', grade:'A Grade' },
  { year:1976, winner:'Bronte Smith', grade:'A Grade' },
  { year:1983, winner:'Adrien Coppen', grade:'B Grade' },
  { year:1987, winner:'Craig Chittleborough', grade:'Senior Colts' },
  { year:1987, winner:'Bronte Smith', grade:'B Grade' },
  { year:1990, winner:'Brenton Daniel', grade:'B Grade' },
  { year:1991, winner:'Matt Oliver', grade:'Junior Colts' },
  { year:1991, winner:'Brendan Kennedy', grade:'A Grade' },
  { year:1992, winner:'Steven Dohnt', grade:'Junior Colts' },
  { year:1993, winner:'Steven Dohnt', grade:'Senior Colts' },
  { year:1995, winner:'Geoff James', grade:'A Grade' },
  { year:2001, winner:'Clint Mansell', grade:'A Grade' },
  { year:2006, winner:'Scott Bown', grade:'Senior Colts' },
  { year:2006, winner:'Brad Page', grade:'B Grade' },
  { year:2007, winner:'Nathan Murphy', grade:'Senior Colts' },
  { year:2008, winner:'Brenton Meier', grade:'B Grade' },
  { year:2010, winner:'Brad Page', grade:'B Grade' },
  { year:2011, winner:'Scott Weger', grade:'Junior Colts' },
  { year:2017, winner:'Jesse May', grade:'B Grade' },
  { year:2019, winner:'Matt Grillett', grade:'B Grade' },
  { year:2024, winner:'Luke Russel', grade:'Senior Colts' },
  { year:2025, winner:'Mitch Miller', grade:'Senior Colts' },
];

export interface GoalKicker { year:number; winner:string; goals:number; }
export const GOAL_KICKERS: GoalKicker[] = [
  { year:1975, winner:'Robert Newhousen', goals:82 },
  { year:1976, winner:'Robert Newhousen', goals:60 },
  { year:1977, winner:'Robert Newhousen', goals:62 },
  { year:1982, winner:'Kym Penney', goals:66 },
  { year:1984, winner:'Ray Higgins', goals:101 },
  { year:1985, winner:'Ray Higgins', goals:65 },
  { year:1990, winner:'Ray Higgins', goals:73 },
  { year:1991, winner:'Kym Penney', goals:69 },
  { year:1995, winner:'Geoff James', goals:153 },
  { year:1996, winner:'Geoff James', goals:141 },
  { year:1997, winner:'Geoff James', goals:123 },
  { year:1998, winner:'Geoff James', goals:128 },
  { year:2001, winner:'Geoff James', goals:95 },
];

export interface LifeMember { year:number; name:string; }
export const LIFE_MEMBERS: LifeMember[] = [
  { year:1945, name:'P. A. Edwards' },
  { year:1947, name:'W. O\'Shea' },
  { year:1947, name:'W. Paull Snr' },
  { year:1947, name:'F. G. (Boase) Hopkins' },
  { year:1947, name:'L. A. Clayton' },
  { year:1948, name:'T. Young' },
  { year:1948, name:'B. McLean' },
  { year:1948, name:'W. L. Buck' },
  { year:1948, name:'J. Pedder' },
  { year:1948, name:'E. McAlees' },
  { year:1949, name:'W. Burgess' },
  { year:1949, name:'G. Green' },
  { year:1949, name:'J. Evans' },
  { year:1949, name:'J. Buck' },
  { year:1950, name:'E. N. Buck' },
  { year:1950, name:'G. Marcus' },
  { year:1955, name:'W. H. Paull' },
  { year:1956, name:'S. H. Westlake' },
  { year:1956, name:'J. Buck Jnr' },
  { year:1956, name:'W. H. Kerslake' },
  { year:1956, name:'L. J. Rosewarne' },
  { year:1956, name:'W. P. Westlake' },
  { year:1956, name:'P. Miller' },
  { year:1956, name:'H. L. Hopkins' },
  { year:1956, name:'J. Simpson' },
  { year:1956, name:'S. McLean' },
  { year:1956, name:'Mrs A. Penney' },
  { year:1956, name:'Mrs S. R. Penney' },
  { year:1956, name:'Mrs P. Smith' },
  { year:1958, name:'L. F. Jones' },
  { year:1958, name:'N. Clarke' },
  { year:1960, name:'L. T. Evans' },
  { year:1960, name:'J. M. W. Kneebone' },
  { year:1961, name:'R. Ladner' },
  { year:1961, name:'Mrs. J. Hopkins' },
  { year:1962, name:'F. J. Pengelley' },
  { year:1964, name:'C. J. Bowman' },
  { year:1965, name:'W. J. McLean' },
  { year:1965, name:'E. C. Simpson' },
  { year:1966, name:'J. K. Smith' },
  { year:1966, name:'R. E. Ross' },
  { year:1969, name:'C. G. Haylock' },
  { year:1969, name:'W. Grillett' },
  { year:1970, name:'Mrs F. Evans' },
  { year:1971, name:'D. R. Shaw' },
  { year:1971, name:'F. E. Hopkins' },
  { year:1979, name:'M. Westlake' },
  { year:1981, name:'Mrs J. Scholefield' },
  { year:1983, name:'S. M. Mellow' },
  { year:1986, name:'J. H. Newhousen' },
  { year:1986, name:'Mrs M. G. Grillett' },
  { year:1987, name:'D. R. Hann' },
  { year:1988, name:'E. J. Penhall' },
  { year:1989, name:'W. F. J. Ladner' },
  { year:1989, name:'L. E. Cooper' },
  { year:1991, name:'R. Newhousen' },
  { year:1991, name:'Mrs M. M. Newhousen' },
  { year:1992, name:'B. Hann' },
  { year:1993, name:'J. T. Evans' },
  { year:1994, name:'P. Willment' },
  { year:1994, name:'G. D. Taylor' },
  { year:1995, name:'B. L. Cooper' },
  { year:1995, name:'A. W. Peters' },
  { year:1996, name:'B. C. Smith' },
  { year:1997, name:'G. O. Tasker' },
  { year:1997, name:'L. L. Johns' },
  { year:1998, name:'A. B. Berry' },
  { year:1998, name:'Mrs J. A. Johns' },
  { year:2000, name:'S. P. Scholes' },
  { year:2001, name:'G. J. Cooper' },
  { year:2001, name:'S. C. Snodgrass' },
  { year:2003, name:'Mrs J. A. Penhall' },
  { year:2005, name:'G. E. J. Davies' },
  { year:2006, name:'M. M. Miller' },
  { year:2008, name:'L. W. Johns' },
  { year:2009, name:'K. P. Flint' },
  { year:2009, name:'L. C. Griffits' },
  { year:2013, name:'D. G. Murphy' },
  { year:2015, name:'D. Miller' },
  { year:2017, name:'S. Grillett' },
  { year:2018, name:'C. Johns' },
  { year:2019, name:'M. Depledge' },
  { year:2019, name:'P. Haylock' },
  { year:2021, name:'Mrs J. Errington' },
  { year:2021, name:'D. Westlake' },
  { year:2023, name:'G. Jarman' },
  { year:2023, name:'G. James' },
  { year:2025, name:'A. West' },
  { year:2025, name:'J. Niotis' },
];

export interface GamesPlayer { name:string; year:number; games:number; }
export const GAMES_CLUB: GamesPlayer[] = [
  { name:'Darren Smith', year:1991, games:390 },
  { name:'Paul Boundy', year:1998, games:276 },
  { name:'Geoff James', year:2006, games:269 },
  { name:'Stephen Scholes', year:1990, games:268 },
  { name:'Chris Johns', year:1995, games:258 },
  { name:'Ian Shaw', year:1993, games:256 },
  { name:'Bradley Page', year:2007, games:253 },
  { name:'Kym Collins', year:1999, games:246 },
  { name:'Darren Price', year:1998, games:228 },
  { name:'David Murphy', year:1991, games:219 },
  { name:'Scott Murphy', year:2015, games:215 },
  { name:'Shaun Miller', year:2009, games:212 },
  { name:'Gary Cooper', year:1990, games:207 },
  { name:'Adrian Boundy', year:2001, games:207 },
  { name:'Tim Nadich', year:2018, games:207 },
  { name:'Stewart Johns', year:2009, games:201 },
  { name:'Matthew Grillett', year:2017, games:198 },
  { name:'Bradley Stewart', year:2003, games:196 },
  { name:'Shane Dalby', year:2006, games:191 },
  { name:'Matthew Bodie', year:2017, games:189 },
  { name:'Kym Flint', year:1992, games:187 },
  { name:'Keith Penhall', year:2004, games:184 },
  { name:'Scott Grillett', year:1994, games:182 },
  { name:'Ben Wall', year:2014, games:182 },
  { name:'David Flint', year:1994, games:179 },
  { name:'Jason Hage', year:2001, games:178 },
  { name:'Darren Kneebone', year:1991, games:172 },
  { name:'Colin Adams', year:1995, games:170 },
  { name:'Kym Penney', year:1991, games:168 },
  { name:'Rowan Green', year:1994, games:167 },
  { name:'Jason Chittleborough', year:2000, games:167 },
  { name:'Reece Page', year:2013, games:165 },
  { name:'Richard Hall', year:2015, games:164 },
  { name:'Brenton Daniel', year:1991, games:163 },
  { name:'Brett Bateson', year:2014, games:163 },
  { name:'Gavin Klinger', year:1992, games:162 },
  { name:'David Thomson', year:1994, games:157 },
  { name:'Ryan Grillett', year:2014, games:155 },
  { name:'Shane Willment', year:2017, games:155 },
  { name:'Daniel Penney', year:2010, games:153 },
  { name:'Shane Dunstan', year:2011, games:153 },
  { name:'Michael Rayner', year:2007, games:152 },
  { name:'Donald Duncan', year:2009, games:152 },
  { name:'Desmond Westlake', year:1993, games:151 },
  { name:'Dylan Boundy', year:2019, games:151 },
  { name:'Lindsay Smith', year:2005, games:0 },
  { name:'Izaak Hann', year:2013, games:0 },
  { name:'Glenn Bretten', year:2017, games:0 },
  { name:'Nathan Murphy', year:2017, games:0 },
  { name:'Todd Summerton', year:2019, games:0 },
  { name:'Thomas Errington', year:2022, games:0 },
  { name:'Dylan Westlake', year:2022, games:0 },
  { name:'Luke Hann', year:2022, games:0 },
  { name:'James Errington', year:2024, games:0 },
  { name:'Chase Martin', year:2026, games:0 },
];
