// Auto-generated from A_GRADE_PREMIERSHIP_PLAYERS.pdf — A Grade premiership honour roll.

export type PremiershipPlayer = {
  surname: string;
  initial: string;
  display: string;   // e.g. "J. Abel"
  years:   number[]; // premiership years
};

export const PREMIERSHIP_PLAYERS: PremiershipPlayer[] = [
  { surname: 'ADAMS', initial: 'D', display: 'D. Adams', years: [1992, 1997, 1998] },
  { surname: 'ADAMS', initial: 'S', display: 'S. Adams', years: [1996, 1997, 1998] },
  { surname: 'ALLEN', initial: 'C', display: 'C. Allen', years: [1914] },
  { surname: 'APPLETON', initial: 'E', display: 'E. Appleton', years: [1902, 1905] },
  { surname: 'AYLIFFE', initial: 'B', display: 'B. Ayliffe', years: [1976] },
  { surname: 'BALDOCK', initial: 'R', display: 'R. Baldock', years: [1945] },
  { surname: 'BARNES', initial: '', display: 'BARNES', years: [1914] },
  { surname: 'BEATTIE', initial: 'J', display: 'J. Beattie', years: [2000] },
  { surname: 'BICKLEY', initial: 'E', display: 'E. Bickley', years: [1952, 1953] },
  { surname: 'BISHOP', initial: 'H', display: 'H. Bishop', years: [1913, 1914, 1915] },
  { surname: 'BISHOP', initial: 'S', display: 'S. Bishop', years: [1915] },
  { surname: 'BISHOP', initial: 'T', display: 'T. Bishop', years: [1905] },
  { surname: 'BOASE', initial: 'M', display: 'M. Boase', years: [1950, 1952, 1953] },
  { surname: 'BOLLMEYER', initial: 'J', display: 'J. Bollmeyer', years: [1926] },
  { surname: 'BOLLMEYER', initial: 'N', display: 'N. Bollmeyer', years: [1983] },
  { surname: 'BORLACE', initial: 'G', display: 'G. Borlace', years: [1976] },
  { surname: 'BOWMAN', initial: 'C', display: 'C. Bowman', years: [1950] },
  { surname: 'BOWN', initial: 'M', display: 'M. Bown', years: [1990, 1992, 1997] },
  { surname: 'BOWN', initial: 'T', display: 'T. Bown', years: [1996, 1998, 2000] },
  { surname: 'BOWN', initial: 'W', display: 'W. Bown', years: [1996, 1997, 1998, 2000] },
  { surname: 'BOYCE', initial: 'L', display: 'L. Boyce', years: [1950] },
  { surname: 'BOYCE', initial: 'M', display: 'M. Boyce', years: [1945] },
  { surname: 'BOYS', initial: 'J', display: 'J. Boys', years: [1976] },
  { surname: 'BRADLEY', initial: 'F', display: 'F. Bradley', years: [1919, 1920] },
  { surname: 'BRADLEY', initial: 'J', display: 'J. Bradley', years: [1919, 1920, 1925] },
  { surname: 'BROADSTOCK', initial: 'P', display: 'P. Broadstock', years: [1950] },
  { surname: 'BROWN', initial: 'E', display: 'E. Brown', years: [1913, 1914, 1915] },
  { surname: 'BROWN', initial: 'H', display: 'H. Brown', years: [1913, 1914, 1915, 1925] },
  { surname: 'BROWN', initial: 'K', display: 'K. Brown', years: [1950, 1952] },
  { surname: 'BROWN Rev A', initial: 'I', display: 'I. Brown Rev A', years: [1925] },
  { surname: 'BRYDEN', initial: 'T', display: 'T. Bryden', years: [1902, 1905] },
  { surname: 'BRYDEN', initial: 'W', display: 'W. Bryden', years: [1902, 1905] },
  { surname: 'BUCK', initial: 'E', display: 'E. Buck', years: [1919, 1926] },
  { surname: 'BUCK', initial: 'G', display: 'G. Buck', years: [1925] },
  { surname: 'BUCK', initial: 'H', display: 'H. Buck', years: [1945] },
  { surname: 'BUCK', initial: 'J', display: 'J. Buck', years: [1945] },
  { surname: 'BULL', initial: 'P', display: 'P. Bull', years: [1952, 1953] },
  { surname: 'BURGESS', initial: 'W', display: 'W. Burgess', years: [1920, 1925] },
  { surname: 'CAMPBELL', initial: 'W', display: 'W. Campbell', years: [1926] },
  { surname: 'CARR', initial: 'D', display: 'D. Carr', years: [1913] },
  { surname: 'CASS', initial: 'J', display: 'J. Cass', years: [1976, 1983] },
  { surname: 'CHANDLER', initial: 'F', display: 'F. Chandler', years: [1926] },
  { surname: 'CHANTRELL', initial: 'D', display: 'D. Chantrell', years: [2000] },
  { surname: 'CHARLESWORTH', initial: 'C', display: 'C. Charlesworth', years: [1919] },
  { surname: 'CHEYNOWETH', initial: 'A', display: 'A. Cheynoweth', years: [1913] },
  { surname: 'CHEYNOWETH', initial: 'H', display: 'H. Cheynoweth', years: [1915, 1920] },
  { surname: 'CHITTLEBOROUGH', initial: 'C', display: 'C. Chittleborough', years: [1990, 1996, 1997, 1998, 2000] },
  { surname: 'CHITTLEBOROUGH', initial: 'J', display: 'J. Chittleborough', years: [1992, 1996, 1997, 1998, 2000] },
  { surname: 'CLARKE', initial: 'H', display: 'H. Clarke', years: [1919] },
  { surname: 'CLARKE', initial: 'N', display: 'N. Clarke', years: [1913, 1914, 1915, 1919, 1920, 1925] },
  { surname: 'CLARKE', initial: 'R', display: 'R. Clarke', years: [1919, 1920] },
  { surname: 'CLAYTON', initial: 'A', display: 'A. Clayton', years: [1913, 1915] },
  { surname: 'CLAYTON', initial: 'E', display: 'E. Clayton', years: [1914] },
  { surname: 'CLAYTON', initial: 'J', display: 'J. Clayton', years: [1945] },
  { surname: 'CLAYTON', initial: 'L', display: 'L. Clayton', years: [1913, 1914, 1915, 1919, 1920, 1925] },
  { surname: 'COBB', initial: 'D', display: 'D. Cobb', years: [1952] },
  { surname: 'COCK', initial: 'R', display: 'R. Cock', years: [1983] },
  { surname: 'CONAUGHTY', initial: 'C', display: 'C. Conaughty', years: [1925] },
  { surname: 'COOPER', initial: 'L', display: 'L. Cooper', years: [1945, 1950] },
  { surname: 'COWARD', initial: 'E', display: 'E. Coward', years: [1919] },
  { surname: 'CRACK', initial: 'A', display: 'A. Crack', years: [2000] },
  { surname: 'CRONIN', initial: 'B', display: 'B. Cronin', years: [1976] },
  { surname: 'CUNNINGHAM', initial: 'G', display: 'G. Cunningham', years: [1952, 1953] },
  { surname: 'DALBY', initial: 'C', display: 'C. Dalby', years: [1945, 1950, 1952] },
  { surname: 'DALBY', initial: 'M', display: 'M. Dalby', years: [1983] },
  { surname: 'DALBY', initial: 'S', display: 'S. Dalby', years: [1998, 2000] },
  { surname: 'DANIEL', initial: 'M', display: 'M. Daniel', years: [1990, 1992, 1996, 1997, 1998] },
  { surname: 'DARE', initial: 'D', display: 'D. Dare', years: [1976] },
  { surname: 'DAVIES', initial: 'H', display: 'H. Davies', years: [1914] },
  { surname: 'DAVIES', initial: 'L', display: 'L. Davies', years: [1913, 1914, 1915] },
  { surname: 'DAVIS', initial: 'K', display: 'K. Davis', years: [1926] },
  { surname: 'DEPLEDGE', initial: 'R', display: 'R. Depledge', years: [1996, 1997, 1998] },
  { surname: 'Des FONTAINES', initial: 'T', display: 'T. Des Fontaines', years: [2000] },
  { surname: 'DOHNT', initial: 'S', display: 'S. Dohnt', years: [1996, 1997, 2000] },
  { surname: 'DONNELL', initial: 'H', display: 'H. Donnell', years: [2000] },
  { surname: 'DOYLE', initial: 'H', display: 'H. Doyle', years: [1913, 1915, 1926] },
  { surname: 'DUNN', initial: 'T', display: 'T. Dunn', years: [1945] },
  { surname: 'EAGLETON', initial: 'E', display: 'E. Eagleton', years: [1950] },
  { surname: 'EAGLETON', initial: 'F', display: 'F. Eagleton', years: [1953] },
  { surname: 'EARCE', initial: 'L', display: 'L. Earce', years: [1992] },
  { surname: 'EDWARDS', initial: 'C', display: 'C. Edwards', years: [1905] },
  { surname: 'EDWARDS', initial: 'M', display: 'M. Edwards', years: [1915] },
  { surname: 'EDWARDS', initial: 'P', display: 'P. Edwards', years: [1905, 1913] },
  { surname: 'ELEY', initial: 'H', display: 'H. Eley', years: [1915] },
  { surname: 'EMES', initial: 'J', display: 'J. Emes', years: [1950, 1952, 1958] },
  { surname: 'EMES', initial: 'W', display: 'W. Emes', years: [1920] },
  { surname: 'EMMS', initial: 'D', display: 'D. Emms', years: [1998] },
  { surname: 'EVANS', initial: 'J', display: 'J. Evans', years: [1976] },
  { surname: 'EVANS', initial: 'Joe', display: 'Joe. Evans', years: [1919, 1920, 1925] },
  { surname: 'EVANS.L', initial: 'T', display: 'T. Evans.L', years: [1945, 1950, 1953, 1954] },
  { surname: 'FAULL', initial: 'D', display: 'D. Faull', years: [1926] },
  { surname: 'FEWINGS', initial: 'B', display: 'B. Fewings', years: [1953] },
  { surname: 'FLINT', initial: 'K', display: 'K. Flint', years: [1983, 1990, 1992] },
  { surname: 'FROST', initial: 'M', display: 'M. Frost', years: [1990] },
  { surname: 'GOLDING', initial: 'L', display: 'L. Golding', years: [1925] },
  { surname: 'GRADE PREMIERSHIP PLAYERS ABEL', initial: 'J', display: 'J. Grade Premiership Players Abel', years: [1954] },
  { surname: 'GREEN', initial: 'C', display: 'C. Green', years: [1945, 1950, 1952, 1953, 1954] },
  { surname: 'GREEN', initial: 'K', display: 'K. Green', years: [1954] },
  { surname: 'GRILLETT', initial: 'B', display: 'B. Grillett', years: [1953, 1954] },
  { surname: 'HANN', initial: 'B', display: 'B. Hann', years: [1976, 1983] },
  { surname: 'HANN', initial: 'S', display: 'S. Hann', years: [1976] },
  { surname: 'HAWSON', initial: 'H', display: 'H. Hawson', years: [1945] },
  { surname: 'HAYLOCK', initial: 'D', display: 'D. Haylock', years: [1976] },
  { surname: 'HERBERT', initial: 'B', display: 'B. Herbert', years: [1926] },
  { surname: 'HIGGINS', initial: 'R', display: 'R. Higgins', years: [1983, 1990, 1992] },
  { surname: 'HOPKINS', initial: 'B', display: 'B. Hopkins', years: [1905] },
  { surname: 'HOPKINS', initial: 'F', display: 'F. Hopkins', years: [1902] },
  { surname: 'HOPKINS', initial: 'Fred', display: 'Fred. Hopkins', years: [1954] },
  { surname: 'HOPKINS', initial: 'J', display: 'J. Hopkins', years: [1925] },
  { surname: 'HOPKINS', initial: 'T', display: 'T. Hopkins', years: [1902] },
  { surname: 'JAMES', initial: 'G', display: 'G. James', years: [1996, 1997, 1998] },
  { surname: 'JAMIESON', initial: 'S', display: 'S. Jamieson', years: [1902] },
  { surname: 'JEFFRIES', initial: 'M', display: 'M. Jeffries', years: [2000] },
  { surname: 'JENKINS', initial: 'R', display: 'R. Jenkins', years: [1945] },
  { surname: 'JINES', initial: 'M', display: 'M. Jines', years: [1905] },
  { surname: 'JOHNS', initial: 'C', display: 'C. Johns', years: [1990, 1992, 1996, 1997, 1998, 2000] },
  { surname: 'JOHNSON', initial: 'G', display: 'G. Johnson', years: [1992] },
  { surname: 'JONES', initial: 'E', display: 'E. Jones', years: [1902] },
  { surname: 'JONES', initial: 'P', display: 'P. Jones', years: [1926] },
  { surname: 'JUCKERS', initial: 'R', display: 'R. Juckers', years: [2000] },
  { surname: 'KELLY', initial: 'M', display: 'M. Kelly', years: [1902, 1905] },
  { surname: 'KELLY', initial: 'W', display: 'W. Kelly', years: [1902] },
  { surname: 'KEMPSTER', initial: 'A', display: 'A. Kempster', years: [1926] },
  { surname: 'KEMPSTER', initial: 'E', display: 'E. Kempster', years: [1926] },
  { surname: 'KENCHINGTON', initial: 'C', display: 'C. Kenchington', years: [1953] },
  { surname: 'KENNEDY', initial: 'B', display: 'B. Kennedy', years: [1990, 1992] },
  { surname: 'KERSLAKE', initial: 'A', display: 'A. Kerslake', years: [1954] },
  { surname: 'KERSLAKE', initial: 'W', display: 'W. Kerslake', years: [1952, 1953, 1954] },
  { surname: 'KESSELL', initial: 'W', display: 'W. Kessell', years: [1905] },
  { surname: 'KIDDY', initial: 'R', display: 'R. Kiddy', years: [1997] },
  { surname: 'KISSELL', initial: 'A', display: 'A. Kissell', years: [1902] },
  { surname: 'KNEEBONE', initial: 'D', display: 'D. Kneebone', years: [1983, 1990] },
  { surname: 'LADN ER', initial: 'A', display: 'A. Ladn Er', years: [1983] },
  { surname: 'LANDER', initial: 'B', display: 'B. Lander', years: [1925] },
  { surname: 'LAWSON', initial: 'D', display: 'D. Lawson', years: [1925] },
  { surname: 'LEWIS', initial: 'P', display: 'P. Lewis', years: [1997] },
  { surname: 'LILIKAKIS', initial: 'M', display: 'M. Lilikakis', years: [1996, 1997] },
  { surname: 'LOUNDER', initial: 'R', display: 'R. Lounder', years: [1996] },
  { surname: 'MANCINI', initial: 'B', display: 'B. Mancini', years: [2000] },
  { surname: 'MARCH', initial: 'S', display: 'S. March', years: [1915] },
  { surname: 'McKEE', initial: 'S', display: 'S. Mckee', years: [1902] },
  { surname: 'McLEAN', initial: 'B', display: 'B. Mclean', years: [1919, 1920, 1925] },
  { surname: 'McLEAN', initial: 'J', display: 'J. Mclean', years: [1952, 1954] },
  { surname: 'MENSFORTH', initial: 'J', display: 'J. Mensforth', years: [1983] },
  { surname: 'MILDWATERS', initial: 'D', display: 'D. Mildwaters', years: [1990] },
  { surname: 'MILLER', initial: 'B', display: 'B. Miller', years: [1950, 1952, 1953, 1954] },
  { surname: 'MILLER', initial: 'M', display: 'M. Miller', years: [1952, 1953, 1954] },
  { surname: 'MILLER', initial: 'P', display: 'P. Miller', years: [1925, 1976] },
  { surname: 'MOORE', initial: 'D', display: 'D. Moore', years: [1902, 1905, 1913] },
  { surname: 'MOORE', initial: 'W', display: 'W. Moore', years: [1915, 1919, 1920] },
  { surname: 'MURPHY', initial: 'D', display: 'D. Murphy', years: [1990] },
  { surname: 'MUTTON', initial: 'L', display: 'L. Mutton', years: [1919, 1920] },
  { surname: 'NEWHOUSEN', initial: 'R', display: 'R. Newhousen', years: [1976] },
  { surname: 'OLDS', initial: 'H', display: 'H. Olds', years: [1945] },
  { surname: 'OLEARY', initial: 'D', display: 'D. Oleary', years: [1919, 1920] },
  { surname: 'OLIVER', initial: 'G', display: 'G. Oliver', years: [1976] },
  { surname: 'OLIVER', initial: 'M', display: 'M. Oliver', years: [1996, 1997, 1998] },
  { surname: 'OLOUGHLIN', initial: 'C', display: 'C. Oloughlin', years: [1926] },
  { surname: 'OLOUGHLIN', initial: 'R', display: 'R. Oloughlin', years: [1926] },
  { surname: 'OWEN', initial: 'D', display: 'D. Owen', years: [1992, 1996, 1997, 1998] },
  { surname: 'OWERS', initial: 'T', display: 'T. Owers', years: [1926] },
  { surname: 'PADDICK', initial: 'M', display: 'M. Paddick', years: [1926] },
  { surname: 'PADDICK', initial: 'Sh', display: 'Sh. Paddick', years: [1997] },
  { surname: 'PAGE', initial: 'B', display: 'B. Page', years: [1998] },
  { surname: 'PAGE', initial: 'D', display: 'D. Page', years: [1990, 1992, 1996] },
  { surname: 'PAULL', initial: 'J', display: 'J. Paull', years: [1926] },
  { surname: 'PAYNE', initial: 'G', display: 'G. Payne', years: [1913, 1915] },
  { surname: 'PEDDAR', initial: 'C', display: 'C. Peddar', years: [1945] },
  { surname: 'PEDDAR', initial: 'F', display: 'F. Peddar', years: [1913, 1914, 1915, 1919] },
  { surname: 'PEDDAR', initial: 'J', display: 'J. Peddar', years: [1913, 1914, 1915, 1919, 1920, 1925] },
  { surname: 'PENNEY', initial: 'D', display: 'D. Penney', years: [2000] },
  { surname: 'PENNEY', initial: 'K', display: 'K. Penney', years: [1983, 1990] },
  { surname: 'PENNEY', initial: 'N', display: 'N. Penney', years: [1905] },
  { surname: 'PENNEY', initial: 'P', display: 'P. Penney', years: [1983] },
  { surname: 'PENNEY', initial: 'W', display: 'W. Penney', years: [1905] },
  { surname: 'PRICE', initial: 'D', display: 'D. Price', years: [1990, 1992, 1996, 2000] },
  { surname: 'PROSSER', initial: 'G', display: 'G. Prosser', years: [1926] },
  { surname: 'RAYMOND', initial: 'N', display: 'N. Raymond', years: [1998] },
  { surname: 'RAYNER', initial: 'M', display: 'M. Rayner', years: [1996, 1997, 1998] },
  { surname: 'REES', initial: 'J', display: 'J. Rees', years: [1902] },
  { surname: 'RICHARDS', initial: 'G', display: 'G. Richards', years: [1950, 1952, 1953] },
  { surname: 'ROSEWARNE', initial: 'L', display: 'L. Rosewarne', years: [1945] },
  { surname: 'ROWE', initial: 'C', display: 'C. Rowe', years: [1926] },
  { surname: 'RYAN', initial: 'J', display: 'J. Ryan', years: [1976] },
  { surname: 'RYLES', initial: 'C', display: 'C. Ryles', years: [1976, 1983] },
  { surname: 'SAMUELS', initial: 'G', display: 'G. Samuels', years: [1919, 1920] },
  { surname: 'SANDF ORD', initial: 'W', display: 'W. Sandf Ord', years: [1914] },
  { surname: 'SCHOLES', initial: 'S', display: 'S. Scholes', years: [1983, 1990, 1992] },
  { surname: 'SELLARS', initial: 'H', display: 'H. Sellars', years: [1914, 1919] },
  { surname: 'SHAW', initial: 'I', display: 'I. Shaw', years: [1990, 1992] },
  { surname: 'SHIELDS', initial: 'S', display: 'S. Shields', years: [1983] },
  { surname: 'SIMPSON', initial: 'D', display: 'D. Simpson', years: [1950, 1952, 1953, 1954] },
  { surname: 'SIMPSON', initial: 'E', display: 'E. Simpson', years: [1950, 1952, 1953, 1954] },
  { surname: 'SIMPSON', initial: 'G', display: 'G. Simpson', years: [1976, 1983] },
  { surname: 'SKINNER', initial: 'B', display: 'B. Skinner', years: [1990] },
  { surname: 'SLEE', initial: 'J', display: 'J. Slee', years: [1976] },
  { surname: 'SMITH', initial: 'B', display: 'B. Smith', years: [1976, 1983] },
  { surname: 'SMITH', initial: 'D', display: 'D. Smith', years: [1952, 1953] },
  { surname: 'SMITH', initial: 'Darren', display: 'Darren. Smith', years: [1983, 1990, 1992] },
  { surname: 'SMITH', initial: 'L', display: 'L. Smith', years: [1998] },
  { surname: 'SMITH.G', initial: 'M', display: 'M. Smith.G', years: [1950, 1952, 1954] },
  { surname: 'SMITH.H', initial: 'J', display: 'J. Smith.H', years: [1950, 1952] },
  { surname: 'SPRY', initial: 'J', display: 'J. Spry', years: [1920] },
  { surname: 'STEER', initial: 'A', display: 'A. Steer', years: [1990, 1992] },
  { surname: 'SURFIELD', initial: 'T', display: 'T. Surfield', years: [1902, 1905] },
  { surname: 'SYMONDS', initial: 'B', display: 'B. Symonds', years: [1913, 1915] },
  { surname: 'SYMONS', initial: 'B', display: 'B. Symons', years: [1905] },
  { surname: 'TAYLOR', initial: 'S', display: 'S. Taylor', years: [1996, 1997, 1998] },
  { surname: 'TESSIERIE', initial: 'L', display: 'L. Tessierie', years: [1920] },
  { surname: 'THOMAS', initial: 'D', display: 'D. Thomas', years: [1954] },
  { surname: 'THOMAS', initial: 'F', display: 'F. Thomas', years: [1926] },
  { surname: 'THOMAS', initial: 'I', display: 'I. Thomas', years: [1976] },
  { surname: 'THOMAS', initial: 'K', display: 'K. Thomas', years: [1952, 1953] },
  { surname: 'THOMAS', initial: 'M', display: 'M. Thomas', years: [1905] },
  { surname: 'THOMAS', initial: 'R', display: 'R. Thomas', years: [1945, 1950] },
  { surname: 'THOMAS', initial: 'T', display: 'T. Thomas', years: [1902] },
  { surname: 'THOMAS', initial: 'W', display: 'W. Thomas', years: [1902] },
  { surname: 'THOMSON', initial: 'D', display: 'D. Thomson', years: [1990, 1992] },
  { surname: 'TOBIN', initial: 'N', display: 'N. Tobin', years: [1976] },
  { surname: 'TOMICH', initial: 'A', display: 'A. Tomich', years: [2000] },
  { surname: 'TREGILGAS', initial: 'S', display: 'S. Tregilgas', years: [1920] },
  { surname: 'UNWIN', initial: 'W', display: 'W. Unwin', years: [1914] },
  { surname: 'UTHILL', initial: 'D', display: 'D. Uthill', years: [2000] },
  { surname: 'WALL', initial: 'J', display: 'J. Wall', years: [2000] },
  { surname: 'WALSH', initial: 'D', display: 'D. Walsh', years: [1914] },
  { surname: 'WARE', initial: 'J', display: 'J. Ware', years: [1950] },
  { surname: 'WATERS', initial: 'M', display: 'M. Waters', years: [1905] },
  { surname: 'WATSON', initial: 'D', display: 'D. Watson', years: [1953] },
  { surname: 'WATTS', initial: 'S', display: 'S. Watts', years: [1983] },
  { surname: 'WECKERT', initial: 'N', display: 'N. Weckert', years: [1992] },
  { surname: 'WESTBROOK', initial: 'I', display: 'I. Westbrook', years: [1983] },
  { surname: 'WESTLAKE', initial: 'M', display: 'M. Westlake', years: [1952, 1953, 1954] },
  { surname: 'WESTLAKE', initial: 'S', display: 'S. Westlake', years: [1945] },
  { surname: 'WHENAN', initial: 'R', display: 'R. Whenan', years: [1913, 1914, 1915] },
  { surname: 'WHITE', initial: 'T', display: 'T. White', years: [1990] },
  { surname: 'WILKINSON', initial: 'J', display: 'J. Wilkinson', years: [1990, 1992, 1996, 1997] },
  { surname: 'WILLIAMS', initial: 'T', display: 'T. Williams', years: [1925] },
  { surname: 'WILLIAMS', initial: 'W', display: 'W. Williams', years: [1902, 1905] },
  { surname: 'WILLMENT', initial: 'G', display: 'G. Willment', years: [2000] },
  { surname: 'WILLMENT', initial: 'P', display: 'P. Willment', years: [1976, 1983] },
  { surname: 'WILLMENT', initial: 'S', display: 'S. Willment', years: [1992, 1996, 1997, 1998] },
  { surname: 'YOUNG', initial: 'R', display: 'R. Young', years: [1925] },
];
